/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import tech.dora.JSON;

/**
 * CouponPayment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-07T12:22:17.571174232+02:00[Europe/Paris]", comments = "Generator version: 7.17.0")
public class CouponPayment {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_ASSET_ID = "asset_id";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nonnull
  private UUID assetId;

  public static final String SERIALIZED_NAME_YIELD = "yield";
  @SerializedName(SERIALIZED_NAME_YIELD)
  @javax.annotation.Nonnull
  private BigDecimal yield;

  public static final String SERIALIZED_NAME_START_AT = "start_at";
  @SerializedName(SERIALIZED_NAME_START_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime startAt;

  public static final String SERIALIZED_NAME_END_AT = "end_at";
  @SerializedName(SERIALIZED_NAME_END_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime endAt;

  public static final String SERIALIZED_NAME_PAY_AT = "pay_at";
  @SerializedName(SERIALIZED_NAME_PAY_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime payAt;

  public static final String SERIALIZED_NAME_AVAILABLE_TO_PAY = "available_to_pay";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_TO_PAY)
  @javax.annotation.Nonnull
  private String availableToPay;

  public static final String SERIALIZED_NAME_COMPLETED_AT = "completed_at";
  @SerializedName(SERIALIZED_NAME_COMPLETED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime completedAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_PROCESS_EVERY = "process_every";
  @SerializedName(SERIALIZED_NAME_PROCESS_EVERY)
  @javax.annotation.Nonnull
  private Integer processEvery;

  public static final String SERIALIZED_NAME_LAST_PROCESSED_AT = "last_processed_at";
  @SerializedName(SERIALIZED_NAME_LAST_PROCESSED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime lastProcessedAt;

  public CouponPayment() {
  }

  public CouponPayment id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public CouponPayment assetId(@javax.annotation.Nonnull UUID assetId) {
    this.assetId = assetId;
    return this;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @javax.annotation.Nonnull
  public UUID getAssetId() {
    return assetId;
  }

  public void setAssetId(@javax.annotation.Nonnull UUID assetId) {
    this.assetId = assetId;
  }


  public CouponPayment yield(@javax.annotation.Nonnull BigDecimal yield) {
    this.yield = yield;
    return this;
  }

  /**
   * Get yield
   * minimum: 0
   * @return yield
   */
  @javax.annotation.Nonnull
  public BigDecimal getYield() {
    return yield;
  }

  public void setYield(@javax.annotation.Nonnull BigDecimal yield) {
    this.yield = yield;
  }


  public CouponPayment startAt(@javax.annotation.Nonnull OffsetDateTime startAt) {
    this.startAt = startAt;
    return this;
  }

  /**
   * Get startAt
   * @return startAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getStartAt() {
    return startAt;
  }

  public void setStartAt(@javax.annotation.Nonnull OffsetDateTime startAt) {
    this.startAt = startAt;
  }


  public CouponPayment endAt(@javax.annotation.Nonnull OffsetDateTime endAt) {
    this.endAt = endAt;
    return this;
  }

  /**
   * Get endAt
   * @return endAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getEndAt() {
    return endAt;
  }

  public void setEndAt(@javax.annotation.Nonnull OffsetDateTime endAt) {
    this.endAt = endAt;
  }


  public CouponPayment payAt(@javax.annotation.Nonnull OffsetDateTime payAt) {
    this.payAt = payAt;
    return this;
  }

  /**
   * Get payAt
   * @return payAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getPayAt() {
    return payAt;
  }

  public void setPayAt(@javax.annotation.Nonnull OffsetDateTime payAt) {
    this.payAt = payAt;
  }


  public CouponPayment availableToPay(@javax.annotation.Nonnull String availableToPay) {
    this.availableToPay = availableToPay;
    return this;
  }

  /**
   * Get availableToPay
   * @return availableToPay
   */
  @javax.annotation.Nonnull
  public String getAvailableToPay() {
    return availableToPay;
  }

  public void setAvailableToPay(@javax.annotation.Nonnull String availableToPay) {
    this.availableToPay = availableToPay;
  }


  public CouponPayment completedAt(@javax.annotation.Nonnull OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

  /**
   * Get completedAt
   * @return completedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(@javax.annotation.Nonnull OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }


  public CouponPayment createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CouponPayment processEvery(@javax.annotation.Nonnull Integer processEvery) {
    this.processEvery = processEvery;
    return this;
  }

  /**
   * Number of nanoseconds to wait between coupon payment processing, must be at least 1000 (1 microsecond)
   * minimum: 1000
   * @return processEvery
   */
  @javax.annotation.Nonnull
  public Integer getProcessEvery() {
    return processEvery;
  }

  public void setProcessEvery(@javax.annotation.Nonnull Integer processEvery) {
    this.processEvery = processEvery;
  }


  public CouponPayment lastProcessedAt(@javax.annotation.Nonnull OffsetDateTime lastProcessedAt) {
    this.lastProcessedAt = lastProcessedAt;
    return this;
  }

  /**
   * Get lastProcessedAt
   * @return lastProcessedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getLastProcessedAt() {
    return lastProcessedAt;
  }

  public void setLastProcessedAt(@javax.annotation.Nonnull OffsetDateTime lastProcessedAt) {
    this.lastProcessedAt = lastProcessedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponPayment couponPayment = (CouponPayment) o;
    return Objects.equals(this.id, couponPayment.id) &&
        Objects.equals(this.assetId, couponPayment.assetId) &&
        Objects.equals(this.yield, couponPayment.yield) &&
        Objects.equals(this.startAt, couponPayment.startAt) &&
        Objects.equals(this.endAt, couponPayment.endAt) &&
        Objects.equals(this.payAt, couponPayment.payAt) &&
        Objects.equals(this.availableToPay, couponPayment.availableToPay) &&
        Objects.equals(this.completedAt, couponPayment.completedAt) &&
        Objects.equals(this.createdAt, couponPayment.createdAt) &&
        Objects.equals(this.processEvery, couponPayment.processEvery) &&
        Objects.equals(this.lastProcessedAt, couponPayment.lastProcessedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, assetId, yield, startAt, endAt, payAt, availableToPay, completedAt, createdAt, processEvery, lastProcessedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponPayment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    yield: ").append(toIndentedString(yield)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    endAt: ").append(toIndentedString(endAt)).append("\n");
    sb.append("    payAt: ").append(toIndentedString(payAt)).append("\n");
    sb.append("    availableToPay: ").append(toIndentedString(availableToPay)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    processEvery: ").append(toIndentedString(processEvery)).append("\n");
    sb.append("    lastProcessedAt: ").append(toIndentedString(lastProcessedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "asset_id", "yield", "start_at", "end_at", "pay_at", "available_to_pay", "completed_at", "created_at", "process_every", "last_processed_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "asset_id", "yield", "start_at", "end_at", "pay_at", "available_to_pay", "completed_at", "created_at", "process_every", "last_processed_at"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CouponPayment
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CouponPayment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in CouponPayment is not found in the empty JSON string", CouponPayment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CouponPayment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CouponPayment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CouponPayment.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("asset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `asset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_id").toString()));
      }
      if (!jsonObj.get("available_to_pay").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `available_to_pay` to be a primitive type in the JSON string but got `%s`", jsonObj.get("available_to_pay").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CouponPayment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CouponPayment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CouponPayment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CouponPayment.class));

       return (TypeAdapter<T>) new TypeAdapter<CouponPayment>() {
           @Override
           public void write(JsonWriter out, CouponPayment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CouponPayment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CouponPayment given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CouponPayment
   * @throws IOException if the JSON string is invalid with respect to CouponPayment
   */
  public static CouponPayment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CouponPayment.class);
  }

  /**
   * Convert an instance of CouponPayment to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

