/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import tech.dora.model.CreateAssetReqCapabilities;
import tech.dora.model.CreateBondReq;
/**
 * CreateAssetReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-07T16:52:00.874312456+02:00[Europe/Paris]")

public class CreateAssetReq {
  @SerializedName("collateral_weight")
  private BigDecimal collateralWeight = null;

  @SerializedName("decimals")
  private Integer decimals = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("max_supply")
  private Integer maxSupply = null;

  @SerializedName("max_utilization")
  private Integer maxUtilization = null;

  @SerializedName("liquidation_threshold")
  private BigDecimal liquidationThreshold = null;

  @SerializedName("symbol")
  private String symbol = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("yield")
  private BigDecimal yield = null;

  @SerializedName("capabilities")
  private CreateAssetReqCapabilities capabilities = null;

  @SerializedName("bond")
  private CreateBondReq bond = null;

  public CreateAssetReq collateralWeight(BigDecimal collateralWeight) {
    this.collateralWeight = collateralWeight;
    return this;
  }

   /**
   * Get collateralWeight
   * @return collateralWeight
  **/
  @Schema(description = "")
  public BigDecimal getCollateralWeight() {
    return collateralWeight;
  }

  public void setCollateralWeight(BigDecimal collateralWeight) {
    this.collateralWeight = collateralWeight;
  }

  public CreateAssetReq decimals(Integer decimals) {
    this.decimals = decimals;
    return this;
  }

   /**
   * Get decimals
   * @return decimals
  **/
  @Schema(description = "")
  public Integer getDecimals() {
    return decimals;
  }

  public void setDecimals(Integer decimals) {
    this.decimals = decimals;
  }

  public CreateAssetReq description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateAssetReq name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateAssetReq maxSupply(Integer maxSupply) {
    this.maxSupply = maxSupply;
    return this;
  }

   /**
   * Get maxSupply
   * @return maxSupply
  **/
  @Schema(description = "")
  public Integer getMaxSupply() {
    return maxSupply;
  }

  public void setMaxSupply(Integer maxSupply) {
    this.maxSupply = maxSupply;
  }

  public CreateAssetReq maxUtilization(Integer maxUtilization) {
    this.maxUtilization = maxUtilization;
    return this;
  }

   /**
   * Get maxUtilization
   * @return maxUtilization
  **/
  @Schema(description = "")
  public Integer getMaxUtilization() {
    return maxUtilization;
  }

  public void setMaxUtilization(Integer maxUtilization) {
    this.maxUtilization = maxUtilization;
  }

  public CreateAssetReq liquidationThreshold(BigDecimal liquidationThreshold) {
    this.liquidationThreshold = liquidationThreshold;
    return this;
  }

   /**
   * Get liquidationThreshold
   * @return liquidationThreshold
  **/
  @Schema(description = "")
  public BigDecimal getLiquidationThreshold() {
    return liquidationThreshold;
  }

  public void setLiquidationThreshold(BigDecimal liquidationThreshold) {
    this.liquidationThreshold = liquidationThreshold;
  }

  public CreateAssetReq symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  @Schema(description = "")
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public CreateAssetReq kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @Schema(description = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public CreateAssetReq yield(BigDecimal yield) {
    this.yield = yield;
    return this;
  }

   /**
   * Get yield
   * @return yield
  **/
  @Schema(description = "")
  public BigDecimal getYield() {
    return yield;
  }

  public void setYield(BigDecimal yield) {
    this.yield = yield;
  }

  public CreateAssetReq capabilities(CreateAssetReqCapabilities capabilities) {
    this.capabilities = capabilities;
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @Schema(description = "")
  public CreateAssetReqCapabilities getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(CreateAssetReqCapabilities capabilities) {
    this.capabilities = capabilities;
  }

  public CreateAssetReq bond(CreateBondReq bond) {
    this.bond = bond;
    return this;
  }

   /**
   * Get bond
   * @return bond
  **/
  @Schema(description = "")
  public CreateBondReq getBond() {
    return bond;
  }

  public void setBond(CreateBondReq bond) {
    this.bond = bond;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAssetReq createAssetReq = (CreateAssetReq) o;
    return Objects.equals(this.collateralWeight, createAssetReq.collateralWeight) &&
        Objects.equals(this.decimals, createAssetReq.decimals) &&
        Objects.equals(this.description, createAssetReq.description) &&
        Objects.equals(this.name, createAssetReq.name) &&
        Objects.equals(this.maxSupply, createAssetReq.maxSupply) &&
        Objects.equals(this.maxUtilization, createAssetReq.maxUtilization) &&
        Objects.equals(this.liquidationThreshold, createAssetReq.liquidationThreshold) &&
        Objects.equals(this.symbol, createAssetReq.symbol) &&
        Objects.equals(this.kind, createAssetReq.kind) &&
        Objects.equals(this.yield, createAssetReq.yield) &&
        Objects.equals(this.capabilities, createAssetReq.capabilities) &&
        Objects.equals(this.bond, createAssetReq.bond);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collateralWeight, decimals, description, name, maxSupply, maxUtilization, liquidationThreshold, symbol, kind, yield, capabilities, bond);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAssetReq {\n");
    
    sb.append("    collateralWeight: ").append(toIndentedString(collateralWeight)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    maxSupply: ").append(toIndentedString(maxSupply)).append("\n");
    sb.append("    maxUtilization: ").append(toIndentedString(maxUtilization)).append("\n");
    sb.append("    liquidationThreshold: ").append(toIndentedString(liquidationThreshold)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    yield: ").append(toIndentedString(yield)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    bond: ").append(toIndentedString(bond)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
