/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tech.dora.JSON;

/**
 * Request to create a USDC withdrawal. No fee quote is required: creating the request reserves the quantity only, and the withdrawal&#39;s fee is quoted and locked later, as part of approval.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-18T18:29:04.763912996+02:00[Europe/Paris]", comments = "Generator version: 7.23.0")
public class CreateWithdrawalRequest {
  public static final String SERIALIZED_NAME_WITHDRAWAL_ID = "withdrawal_id";
  @SerializedName(SERIALIZED_NAME_WITHDRAWAL_ID)
  @javax.annotation.Nonnull
  private UUID withdrawalId;

  public static final String SERIALIZED_NAME_TO_ADDRESS = "to_address";
  @SerializedName(SERIALIZED_NAME_TO_ADDRESS)
  @javax.annotation.Nonnull
  private String toAddress;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nonnull
  private String quantity;

  public CreateWithdrawalRequest() {
  }

  public CreateWithdrawalRequest withdrawalId(@javax.annotation.Nonnull UUID withdrawalId) {
    this.withdrawalId = withdrawalId;
    return this;
  }

  /**
   * Client-supplied idempotency key (also the on-chain correlation key). Repeating a request with the same withdrawal_id has no additional effect.
   * @return withdrawalId
   */
  @javax.annotation.Nonnull
  public UUID getWithdrawalId() {
    return withdrawalId;
  }

  public void setWithdrawalId(@javax.annotation.Nonnull UUID withdrawalId) {
    this.withdrawalId = withdrawalId;
  }


  public CreateWithdrawalRequest toAddress(@javax.annotation.Nonnull String toAddress) {
    this.toAddress = toAddress;
    return this;
  }

  /**
   * Destination wallet address as a 0x-prefixed hex string. Must not be the zero address.
   * @return toAddress
   */
  @javax.annotation.Nonnull
  public String getToAddress() {
    return toAddress;
  }

  public void setToAddress(@javax.annotation.Nonnull String toAddress) {
    this.toAddress = toAddress;
  }


  public CreateWithdrawalRequest quantity(@javax.annotation.Nonnull String quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Human-decimal USDC quantity to withdraw. Must be positive and no finer than USDC&#39;s 6 on-chain decimals.
   * @return quantity
   */
  @javax.annotation.Nonnull
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nonnull String quantity) {
    this.quantity = quantity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWithdrawalRequest createWithdrawalRequest = (CreateWithdrawalRequest) o;
    return Objects.equals(this.withdrawalId, createWithdrawalRequest.withdrawalId) &&
        Objects.equals(this.toAddress, createWithdrawalRequest.toAddress) &&
        Objects.equals(this.quantity, createWithdrawalRequest.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(withdrawalId, toAddress, quantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWithdrawalRequest {\n");
    sb.append("    withdrawalId: ").append(toIndentedString(withdrawalId)).append("\n");
    sb.append("    toAddress: ").append(toIndentedString(toAddress)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("withdrawal_id", "to_address", "quantity"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("withdrawal_id", "to_address", "quantity"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateWithdrawalRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateWithdrawalRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateWithdrawalRequest is not found in the empty JSON string", CreateWithdrawalRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateWithdrawalRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateWithdrawalRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateWithdrawalRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("withdrawal_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `withdrawal_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("withdrawal_id").toString()));
      }
      if (!jsonObj.get("to_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `to_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to_address").toString()));
      }
      if (!jsonObj.get("quantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `quantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quantity").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateWithdrawalRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateWithdrawalRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateWithdrawalRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateWithdrawalRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateWithdrawalRequest>() {
           @Override
           public void write(JsonWriter out, CreateWithdrawalRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateWithdrawalRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateWithdrawalRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateWithdrawalRequest
   * @throws IOException if the JSON string is invalid with respect to CreateWithdrawalRequest
   */
  public static CreateWithdrawalRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateWithdrawalRequest.class);
  }

  /**
   * Convert an instance of CreateWithdrawalRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

