/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import tech.dora.JSON;

/**
 * CurrentLeverageAccruedInterest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-29T20:52:14.700905316+02:00[Europe/Paris]", comments = "Generator version: 7.17.0")
public class CurrentLeverageAccruedInterest {
  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nonnull
  private UUID userId;

  public static final String SERIALIZED_NAME_ASSET_ID = "asset_id";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nonnull
  private UUID assetId;

  public static final String SERIALIZED_NAME_POSITION_ID = "position_id";
  @SerializedName(SERIALIZED_NAME_POSITION_ID)
  @javax.annotation.Nonnull
  private UUID positionId;

  public static final String SERIALIZED_NAME_CURRENT_ACCRUED_INTEREST_USD = "current_accrued_interest_usd";
  @SerializedName(SERIALIZED_NAME_CURRENT_ACCRUED_INTEREST_USD)
  @javax.annotation.Nonnull
  private String currentAccruedInterestUsd;

  public static final String SERIALIZED_NAME_ASSET_NAME = "asset_name";
  @SerializedName(SERIALIZED_NAME_ASSET_NAME)
  @javax.annotation.Nullable
  private String assetName;

  public static final String SERIALIZED_NAME_ASSET_SYMBOL = "asset_symbol";
  @SerializedName(SERIALIZED_NAME_ASSET_SYMBOL)
  @javax.annotation.Nullable
  private String assetSymbol;

  public CurrentLeverageAccruedInterest() {
  }

  public CurrentLeverageAccruedInterest userId(@javax.annotation.Nonnull UUID userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nonnull
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nonnull UUID userId) {
    this.userId = userId;
  }


  public CurrentLeverageAccruedInterest assetId(@javax.annotation.Nonnull UUID assetId) {
    this.assetId = assetId;
    return this;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @javax.annotation.Nonnull
  public UUID getAssetId() {
    return assetId;
  }

  public void setAssetId(@javax.annotation.Nonnull UUID assetId) {
    this.assetId = assetId;
  }


  public CurrentLeverageAccruedInterest positionId(@javax.annotation.Nonnull UUID positionId) {
    this.positionId = positionId;
    return this;
  }

  /**
   * Get positionId
   * @return positionId
   */
  @javax.annotation.Nonnull
  public UUID getPositionId() {
    return positionId;
  }

  public void setPositionId(@javax.annotation.Nonnull UUID positionId) {
    this.positionId = positionId;
  }


  public CurrentLeverageAccruedInterest currentAccruedInterestUsd(@javax.annotation.Nonnull String currentAccruedInterestUsd) {
    this.currentAccruedInterestUsd = currentAccruedInterestUsd;
    return this;
  }

  /**
   * Get currentAccruedInterestUsd
   * @return currentAccruedInterestUsd
   */
  @javax.annotation.Nonnull
  public String getCurrentAccruedInterestUsd() {
    return currentAccruedInterestUsd;
  }

  public void setCurrentAccruedInterestUsd(@javax.annotation.Nonnull String currentAccruedInterestUsd) {
    this.currentAccruedInterestUsd = currentAccruedInterestUsd;
  }


  public CurrentLeverageAccruedInterest assetName(@javax.annotation.Nullable String assetName) {
    this.assetName = assetName;
    return this;
  }

  /**
   * Get assetName
   * @return assetName
   */
  @javax.annotation.Nullable
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(@javax.annotation.Nullable String assetName) {
    this.assetName = assetName;
  }


  public CurrentLeverageAccruedInterest assetSymbol(@javax.annotation.Nullable String assetSymbol) {
    this.assetSymbol = assetSymbol;
    return this;
  }

  /**
   * Get assetSymbol
   * @return assetSymbol
   */
  @javax.annotation.Nullable
  public String getAssetSymbol() {
    return assetSymbol;
  }

  public void setAssetSymbol(@javax.annotation.Nullable String assetSymbol) {
    this.assetSymbol = assetSymbol;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrentLeverageAccruedInterest currentLeverageAccruedInterest = (CurrentLeverageAccruedInterest) o;
    return Objects.equals(this.userId, currentLeverageAccruedInterest.userId) &&
        Objects.equals(this.assetId, currentLeverageAccruedInterest.assetId) &&
        Objects.equals(this.positionId, currentLeverageAccruedInterest.positionId) &&
        Objects.equals(this.currentAccruedInterestUsd, currentLeverageAccruedInterest.currentAccruedInterestUsd) &&
        Objects.equals(this.assetName, currentLeverageAccruedInterest.assetName) &&
        Objects.equals(this.assetSymbol, currentLeverageAccruedInterest.assetSymbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, assetId, positionId, currentAccruedInterestUsd, assetName, assetSymbol);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrentLeverageAccruedInterest {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    positionId: ").append(toIndentedString(positionId)).append("\n");
    sb.append("    currentAccruedInterestUsd: ").append(toIndentedString(currentAccruedInterestUsd)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    assetSymbol: ").append(toIndentedString(assetSymbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("user_id", "asset_id", "position_id", "current_accrued_interest_usd", "asset_name", "asset_symbol"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("user_id", "asset_id", "position_id", "current_accrued_interest_usd"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CurrentLeverageAccruedInterest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CurrentLeverageAccruedInterest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in CurrentLeverageAccruedInterest is not found in the empty JSON string", CurrentLeverageAccruedInterest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CurrentLeverageAccruedInterest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CurrentLeverageAccruedInterest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CurrentLeverageAccruedInterest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
      if (!jsonObj.get("asset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `asset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_id").toString()));
      }
      if (!jsonObj.get("position_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `position_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("position_id").toString()));
      }
      if (!jsonObj.get("current_accrued_interest_usd").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `current_accrued_interest_usd` to be a primitive type in the JSON string but got `%s`", jsonObj.get("current_accrued_interest_usd").toString()));
      }
      if ((jsonObj.get("asset_name") != null && !jsonObj.get("asset_name").isJsonNull()) && !jsonObj.get("asset_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `asset_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_name").toString()));
      }
      if ((jsonObj.get("asset_symbol") != null && !jsonObj.get("asset_symbol").isJsonNull()) && !jsonObj.get("asset_symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `asset_symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_symbol").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CurrentLeverageAccruedInterest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CurrentLeverageAccruedInterest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CurrentLeverageAccruedInterest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CurrentLeverageAccruedInterest.class));

       return (TypeAdapter<T>) new TypeAdapter<CurrentLeverageAccruedInterest>() {
           @Override
           public void write(JsonWriter out, CurrentLeverageAccruedInterest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CurrentLeverageAccruedInterest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CurrentLeverageAccruedInterest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CurrentLeverageAccruedInterest
   * @throws IOException if the JSON string is invalid with respect to CurrentLeverageAccruedInterest
   */
  public static CurrentLeverageAccruedInterest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CurrentLeverageAccruedInterest.class);
  }

  /**
   * Convert an instance of CurrentLeverageAccruedInterest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

