/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import tech.dora.model.FundUser;
import tech.dora.model.Metadata;
import tech.dora.model.ResponseEnvelope;
/**
 * FundUserResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-31T14:07:25.766711372+02:00[Europe/Paris]")

public class FundUserResponse extends ResponseEnvelope {
  @SerializedName("data")
  private FundUser fundUserResponseData = null;

  public FundUserResponse fundUserResponseData(FundUser fundUserResponseData) {
    this.fundUserResponseData = fundUserResponseData;
    return this;
  }

   /**
   * Get fundUserResponseData
   * @return fundUserResponseData
  **/
  @Schema(description = "")
  public FundUser getFundUserResponseData() {
    return fundUserResponseData;
  }

  public void setFundUserResponseData(FundUser fundUserResponseData) {
    this.fundUserResponseData = fundUserResponseData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundUserResponse fundUserResponse = (FundUserResponse) o;
    return Objects.equals(this.fundUserResponseData, fundUserResponse.fundUserResponseData) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fundUserResponseData, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundUserResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    fundUserResponseData: ").append(toIndentedString(fundUserResponseData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
