/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import tech.dora.model.Metadata;
import tech.dora.model.OrderBookTop;
import tech.dora.model.ResponseEnvelope;
/**
 * GetTopOfBookResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-09-23T16:14:25.446198532+02:00[Europe/Paris]")

public class GetTopOfBookResponse extends ResponseEnvelope {
  @SerializedName("data")
  private OrderBookTop getTopOfBookResponseData = null;

  public GetTopOfBookResponse getTopOfBookResponseData(OrderBookTop getTopOfBookResponseData) {
    this.getTopOfBookResponseData = getTopOfBookResponseData;
    return this;
  }

   /**
   * Get getTopOfBookResponseData
   * @return getTopOfBookResponseData
  **/
  @Schema(description = "")
  public OrderBookTop getGetTopOfBookResponseData() {
    return getTopOfBookResponseData;
  }

  public void setGetTopOfBookResponseData(OrderBookTop getTopOfBookResponseData) {
    this.getTopOfBookResponseData = getTopOfBookResponseData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTopOfBookResponse getTopOfBookResponse = (GetTopOfBookResponse) o;
    return Objects.equals(this.getTopOfBookResponseData, getTopOfBookResponse.getTopOfBookResponseData) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(getTopOfBookResponseData, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTopOfBookResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    getTopOfBookResponseData: ").append(toIndentedString(getTopOfBookResponseData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
