/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import tech.dora.model.HistoricalLeverageInterestRates;
import tech.dora.model.Metadata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tech.dora.JSON;

/**
 * HistoricalLeverageInterestRatesResponseEnvelope
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-23T16:44:58.682065994+02:00[Europe/Paris]", comments = "Generator version: 7.23.0")
public class HistoricalLeverageInterestRatesResponseEnvelope {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private HistoricalLeverageInterestRates data;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  @javax.annotation.Nullable
  private String error;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nonnull
  private Metadata metadata;

  public HistoricalLeverageInterestRatesResponseEnvelope() {
  }

  public HistoricalLeverageInterestRatesResponseEnvelope data(@javax.annotation.Nullable HistoricalLeverageInterestRates data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  public HistoricalLeverageInterestRates getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable HistoricalLeverageInterestRates data) {
    this.data = data;
  }


  public HistoricalLeverageInterestRatesResponseEnvelope error(@javax.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * The error message. Present for error (non-2xx) responses.
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(@javax.annotation.Nullable String error) {
    this.error = error;
  }


  public HistoricalLeverageInterestRatesResponseEnvelope metadata(@javax.annotation.Nonnull Metadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Metadata about the response, including status code and trace information.
   * @return metadata
   */
  @javax.annotation.Nonnull
  public Metadata getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nonnull Metadata metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalLeverageInterestRatesResponseEnvelope historicalLeverageInterestRatesResponseEnvelope = (HistoricalLeverageInterestRatesResponseEnvelope) o;
    return Objects.equals(this.data, historicalLeverageInterestRatesResponseEnvelope.data) &&
        Objects.equals(this.error, historicalLeverageInterestRatesResponseEnvelope.error) &&
        Objects.equals(this.metadata, historicalLeverageInterestRatesResponseEnvelope.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, error, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalLeverageInterestRatesResponseEnvelope {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("data", "error", "metadata"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("metadata"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HistoricalLeverageInterestRatesResponseEnvelope
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HistoricalLeverageInterestRatesResponseEnvelope.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in HistoricalLeverageInterestRatesResponseEnvelope is not found in the empty JSON string", HistoricalLeverageInterestRatesResponseEnvelope.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HistoricalLeverageInterestRatesResponseEnvelope.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HistoricalLeverageInterestRatesResponseEnvelope` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HistoricalLeverageInterestRatesResponseEnvelope.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `data`
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) {
        HistoricalLeverageInterestRates.validateJsonElement(jsonObj.get("data"));
      }
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
      // validate the required field `metadata`
      Metadata.validateJsonElement(jsonObj.get("metadata"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HistoricalLeverageInterestRatesResponseEnvelope.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HistoricalLeverageInterestRatesResponseEnvelope' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HistoricalLeverageInterestRatesResponseEnvelope> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HistoricalLeverageInterestRatesResponseEnvelope.class));

       return (TypeAdapter<T>) new TypeAdapter<HistoricalLeverageInterestRatesResponseEnvelope>() {
           @Override
           public void write(JsonWriter out, HistoricalLeverageInterestRatesResponseEnvelope value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HistoricalLeverageInterestRatesResponseEnvelope read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HistoricalLeverageInterestRatesResponseEnvelope given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HistoricalLeverageInterestRatesResponseEnvelope
   * @throws IOException if the JSON string is invalid with respect to HistoricalLeverageInterestRatesResponseEnvelope
   */
  public static HistoricalLeverageInterestRatesResponseEnvelope fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HistoricalLeverageInterestRatesResponseEnvelope.class);
  }

  /**
   * Convert an instance of HistoricalLeverageInterestRatesResponseEnvelope to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

