/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import tech.dora.JSON;

/**
 * HistoricalLeverageInterestRate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-02T17:13:50.947925667+02:00[Europe/Paris]", comments = "Generator version: 7.17.0")
public class HistoricalLeverageInterestRate {
  public static final String SERIALIZED_NAME_ASSET_ID = "asset_id";
  @SerializedName(SERIALIZED_NAME_ASSET_ID)
  @javax.annotation.Nonnull
  private UUID assetId;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_UTILIZATION = "utilization";
  @SerializedName(SERIALIZED_NAME_UTILIZATION)
  @javax.annotation.Nonnull
  private BigDecimal utilization;

  public static final String SERIALIZED_NAME_MAXIMUM_UTILIZATION = "maximum_utilization";
  @SerializedName(SERIALIZED_NAME_MAXIMUM_UTILIZATION)
  @javax.annotation.Nonnull
  private BigDecimal maximumUtilization;

  public static final String SERIALIZED_NAME_MINIMUM_RATE = "minimum_rate";
  @SerializedName(SERIALIZED_NAME_MINIMUM_RATE)
  @javax.annotation.Nonnull
  private BigDecimal minimumRate;

  public static final String SERIALIZED_NAME_KINK_RATE = "kink_rate";
  @SerializedName(SERIALIZED_NAME_KINK_RATE)
  @javax.annotation.Nonnull
  private BigDecimal kinkRate;

  public static final String SERIALIZED_NAME_MAXIMUM_RATE = "maximum_rate";
  @SerializedName(SERIALIZED_NAME_MAXIMUM_RATE)
  @javax.annotation.Nonnull
  private BigDecimal maximumRate;

  public static final String SERIALIZED_NAME_KINK_UTILIZATION = "kink_utilization";
  @SerializedName(SERIALIZED_NAME_KINK_UTILIZATION)
  @javax.annotation.Nonnull
  private BigDecimal kinkUtilization;

  public static final String SERIALIZED_NAME_INTEREST_RATE = "interest_rate";
  @SerializedName(SERIALIZED_NAME_INTEREST_RATE)
  @javax.annotation.Nonnull
  private BigDecimal interestRate;

  public HistoricalLeverageInterestRate() {
  }

  public HistoricalLeverageInterestRate assetId(@javax.annotation.Nonnull UUID assetId) {
    this.assetId = assetId;
    return this;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @javax.annotation.Nonnull
  public UUID getAssetId() {
    return assetId;
  }

  public void setAssetId(@javax.annotation.Nonnull UUID assetId) {
    this.assetId = assetId;
  }


  public HistoricalLeverageInterestRate updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public HistoricalLeverageInterestRate utilization(@javax.annotation.Nonnull BigDecimal utilization) {
    this.utilization = utilization;
    return this;
  }

  /**
   * Get utilization
   * @return utilization
   */
  @javax.annotation.Nonnull
  public BigDecimal getUtilization() {
    return utilization;
  }

  public void setUtilization(@javax.annotation.Nonnull BigDecimal utilization) {
    this.utilization = utilization;
  }


  public HistoricalLeverageInterestRate maximumUtilization(@javax.annotation.Nonnull BigDecimal maximumUtilization) {
    this.maximumUtilization = maximumUtilization;
    return this;
  }

  /**
   * Get maximumUtilization
   * @return maximumUtilization
   */
  @javax.annotation.Nonnull
  public BigDecimal getMaximumUtilization() {
    return maximumUtilization;
  }

  public void setMaximumUtilization(@javax.annotation.Nonnull BigDecimal maximumUtilization) {
    this.maximumUtilization = maximumUtilization;
  }


  public HistoricalLeverageInterestRate minimumRate(@javax.annotation.Nonnull BigDecimal minimumRate) {
    this.minimumRate = minimumRate;
    return this;
  }

  /**
   * Get minimumRate
   * @return minimumRate
   */
  @javax.annotation.Nonnull
  public BigDecimal getMinimumRate() {
    return minimumRate;
  }

  public void setMinimumRate(@javax.annotation.Nonnull BigDecimal minimumRate) {
    this.minimumRate = minimumRate;
  }


  public HistoricalLeverageInterestRate kinkRate(@javax.annotation.Nonnull BigDecimal kinkRate) {
    this.kinkRate = kinkRate;
    return this;
  }

  /**
   * Get kinkRate
   * @return kinkRate
   */
  @javax.annotation.Nonnull
  public BigDecimal getKinkRate() {
    return kinkRate;
  }

  public void setKinkRate(@javax.annotation.Nonnull BigDecimal kinkRate) {
    this.kinkRate = kinkRate;
  }


  public HistoricalLeverageInterestRate maximumRate(@javax.annotation.Nonnull BigDecimal maximumRate) {
    this.maximumRate = maximumRate;
    return this;
  }

  /**
   * Get maximumRate
   * @return maximumRate
   */
  @javax.annotation.Nonnull
  public BigDecimal getMaximumRate() {
    return maximumRate;
  }

  public void setMaximumRate(@javax.annotation.Nonnull BigDecimal maximumRate) {
    this.maximumRate = maximumRate;
  }


  public HistoricalLeverageInterestRate kinkUtilization(@javax.annotation.Nonnull BigDecimal kinkUtilization) {
    this.kinkUtilization = kinkUtilization;
    return this;
  }

  /**
   * Get kinkUtilization
   * @return kinkUtilization
   */
  @javax.annotation.Nonnull
  public BigDecimal getKinkUtilization() {
    return kinkUtilization;
  }

  public void setKinkUtilization(@javax.annotation.Nonnull BigDecimal kinkUtilization) {
    this.kinkUtilization = kinkUtilization;
  }


  public HistoricalLeverageInterestRate interestRate(@javax.annotation.Nonnull BigDecimal interestRate) {
    this.interestRate = interestRate;
    return this;
  }

  /**
   * Get interestRate
   * @return interestRate
   */
  @javax.annotation.Nonnull
  public BigDecimal getInterestRate() {
    return interestRate;
  }

  public void setInterestRate(@javax.annotation.Nonnull BigDecimal interestRate) {
    this.interestRate = interestRate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalLeverageInterestRate historicalLeverageInterestRate = (HistoricalLeverageInterestRate) o;
    return Objects.equals(this.assetId, historicalLeverageInterestRate.assetId) &&
        Objects.equals(this.updatedAt, historicalLeverageInterestRate.updatedAt) &&
        Objects.equals(this.utilization, historicalLeverageInterestRate.utilization) &&
        Objects.equals(this.maximumUtilization, historicalLeverageInterestRate.maximumUtilization) &&
        Objects.equals(this.minimumRate, historicalLeverageInterestRate.minimumRate) &&
        Objects.equals(this.kinkRate, historicalLeverageInterestRate.kinkRate) &&
        Objects.equals(this.maximumRate, historicalLeverageInterestRate.maximumRate) &&
        Objects.equals(this.kinkUtilization, historicalLeverageInterestRate.kinkUtilization) &&
        Objects.equals(this.interestRate, historicalLeverageInterestRate.interestRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetId, updatedAt, utilization, maximumUtilization, minimumRate, kinkRate, maximumRate, kinkUtilization, interestRate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalLeverageInterestRate {\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    utilization: ").append(toIndentedString(utilization)).append("\n");
    sb.append("    maximumUtilization: ").append(toIndentedString(maximumUtilization)).append("\n");
    sb.append("    minimumRate: ").append(toIndentedString(minimumRate)).append("\n");
    sb.append("    kinkRate: ").append(toIndentedString(kinkRate)).append("\n");
    sb.append("    maximumRate: ").append(toIndentedString(maximumRate)).append("\n");
    sb.append("    kinkUtilization: ").append(toIndentedString(kinkUtilization)).append("\n");
    sb.append("    interestRate: ").append(toIndentedString(interestRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("asset_id", "updated_at", "utilization", "maximum_utilization", "minimum_rate", "kink_rate", "maximum_rate", "kink_utilization", "interest_rate"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("asset_id", "updated_at", "utilization", "maximum_utilization", "minimum_rate", "kink_rate", "maximum_rate", "kink_utilization", "interest_rate"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HistoricalLeverageInterestRate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HistoricalLeverageInterestRate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in HistoricalLeverageInterestRate is not found in the empty JSON string", HistoricalLeverageInterestRate.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HistoricalLeverageInterestRate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HistoricalLeverageInterestRate` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HistoricalLeverageInterestRate.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("asset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `asset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("asset_id").toString()));
      }
      if (!jsonObj.get("utilization").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `utilization` to be a primitive type in the JSON string but got `%s`", jsonObj.get("utilization").toString()));
      }
      if (!jsonObj.get("maximum_utilization").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `maximum_utilization` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maximum_utilization").toString()));
      }
      if (!jsonObj.get("minimum_rate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `minimum_rate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("minimum_rate").toString()));
      }
      if (!jsonObj.get("kink_rate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `kink_rate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kink_rate").toString()));
      }
      if (!jsonObj.get("maximum_rate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `maximum_rate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maximum_rate").toString()));
      }
      if (!jsonObj.get("kink_utilization").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `kink_utilization` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kink_utilization").toString()));
      }
      if (!jsonObj.get("interest_rate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `interest_rate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("interest_rate").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HistoricalLeverageInterestRate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HistoricalLeverageInterestRate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HistoricalLeverageInterestRate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HistoricalLeverageInterestRate.class));

       return (TypeAdapter<T>) new TypeAdapter<HistoricalLeverageInterestRate>() {
           @Override
           public void write(JsonWriter out, HistoricalLeverageInterestRate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HistoricalLeverageInterestRate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HistoricalLeverageInterestRate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HistoricalLeverageInterestRate
   * @throws IOException if the JSON string is invalid with respect to HistoricalLeverageInterestRate
   */
  public static HistoricalLeverageInterestRate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HistoricalLeverageInterestRate.class);
  }

  /**
   * Convert an instance of HistoricalLeverageInterestRate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

