/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import tech.dora.model.Metadata;
import tech.dora.model.OrderbookBalance;
import tech.dora.model.ResponseEnvelope;
/**
 * InlineResponse20014
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-17T12:01:43.728636988+02:00[Europe/Paris]")

public class InlineResponse20014 extends ResponseEnvelope {
  @SerializedName("data")
  private OrderbookBalance inlineResponse20014Data = null;

  public InlineResponse20014 inlineResponse20014Data(OrderbookBalance inlineResponse20014Data) {
    this.inlineResponse20014Data = inlineResponse20014Data;
    return this;
  }

   /**
   * Get inlineResponse20014Data
   * @return inlineResponse20014Data
  **/
  @Schema(description = "")
  public OrderbookBalance getInlineResponse20014Data() {
    return inlineResponse20014Data;
  }

  public void setInlineResponse20014Data(OrderbookBalance inlineResponse20014Data) {
    this.inlineResponse20014Data = inlineResponse20014Data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20014 inlineResponse20014 = (InlineResponse20014) o;
    return Objects.equals(this.inlineResponse20014Data, inlineResponse20014.inlineResponse20014Data) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inlineResponse20014Data, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20014 {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    inlineResponse20014Data: ").append(toIndentedString(inlineResponse20014Data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
