/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import tech.dora.model.AssetPrice;
import tech.dora.model.Metadata;
import tech.dora.model.ResponseEnvelope;
/**
 * InlineResponse200
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-31T14:00:14.316927622+02:00[Europe/Paris]")

public class InlineResponse200 extends ResponseEnvelope {
  @SerializedName("data")
  private List<AssetPrice> inlineResponse200Data = null;

  public InlineResponse200 inlineResponse200Data(List<AssetPrice> inlineResponse200Data) {
    this.inlineResponse200Data = inlineResponse200Data;
    return this;
  }

  public InlineResponse200 addInlineResponse200DataItem(AssetPrice inlineResponse200DataItem) {
    if (this.inlineResponse200Data == null) {
      this.inlineResponse200Data = new ArrayList<AssetPrice>();
    }
    this.inlineResponse200Data.add(inlineResponse200DataItem);
    return this;
  }

   /**
   * Get inlineResponse200Data
   * @return inlineResponse200Data
  **/
  @Schema(description = "")
  public List<AssetPrice> getInlineResponse200Data() {
    return inlineResponse200Data;
  }

  public void setInlineResponse200Data(List<AssetPrice> inlineResponse200Data) {
    this.inlineResponse200Data = inlineResponse200Data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.inlineResponse200Data, inlineResponse200.inlineResponse200Data) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inlineResponse200Data, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    inlineResponse200Data: ").append(toIndentedString(inlineResponse200Data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
