/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import tech.dora.model.Candle;
import tech.dora.model.Metadata;
import tech.dora.model.ResponseEnvelope;
/**
 * InlineResponse20017
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-17T12:01:43.728636988+02:00[Europe/Paris]")

public class InlineResponse20017 extends ResponseEnvelope {
  @SerializedName("data")
  private List<Candle> inlineResponse20017Data = null;

  public InlineResponse20017 inlineResponse20017Data(List<Candle> inlineResponse20017Data) {
    this.inlineResponse20017Data = inlineResponse20017Data;
    return this;
  }

  public InlineResponse20017 addInlineResponse20017DataItem(Candle inlineResponse20017DataItem) {
    if (this.inlineResponse20017Data == null) {
      this.inlineResponse20017Data = new ArrayList<Candle>();
    }
    this.inlineResponse20017Data.add(inlineResponse20017DataItem);
    return this;
  }

   /**
   * Get inlineResponse20017Data
   * @return inlineResponse20017Data
  **/
  @Schema(description = "")
  public List<Candle> getInlineResponse20017Data() {
    return inlineResponse20017Data;
  }

  public void setInlineResponse20017Data(List<Candle> inlineResponse20017Data) {
    this.inlineResponse20017Data = inlineResponse20017Data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20017 inlineResponse20017 = (InlineResponse20017) o;
    return Objects.equals(this.inlineResponse20017Data, inlineResponse20017.inlineResponse20017Data) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inlineResponse20017Data, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20017 {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    inlineResponse20017Data: ").append(toIndentedString(inlineResponse20017Data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
