/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
/**
 * LiquidityRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-07T16:52:00.874312456+02:00[Europe/Paris]")

public class LiquidityRequest {
  @SerializedName("order_book_id")
  private UUID orderBookId = null;

  @SerializedName("position_id")
  private UUID positionId = null;

  @SerializedName("quantity")
  private String quantity = null;

  public LiquidityRequest orderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
    return this;
  }

   /**
   * Get orderBookId
   * @return orderBookId
  **/
  @Schema(description = "")
  public UUID getOrderBookId() {
    return orderBookId;
  }

  public void setOrderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
  }

  public LiquidityRequest positionId(UUID positionId) {
    this.positionId = positionId;
    return this;
  }

   /**
   * Get positionId
   * @return positionId
  **/
  @Schema(description = "")
  public UUID getPositionId() {
    return positionId;
  }

  public void setPositionId(UUID positionId) {
    this.positionId = positionId;
  }

  public LiquidityRequest quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiquidityRequest liquidityRequest = (LiquidityRequest) o;
    return Objects.equals(this.orderBookId, liquidityRequest.orderBookId) &&
        Objects.equals(this.positionId, liquidityRequest.positionId) &&
        Objects.equals(this.quantity, liquidityRequest.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderBookId, positionId, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiquidityRequest {\n");
    
    sb.append("    orderBookId: ").append(toIndentedString(orderBookId)).append("\n");
    sb.append("    positionId: ").append(toIndentedString(positionId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
