/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import tech.dora.model.CouponPayment;
import tech.dora.model.Metadata;
import tech.dora.model.ResponseEnvelope;
/**
 * ListCouponPaymentsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-30T15:33:45.934694888+02:00[Europe/Paris]")

public class ListCouponPaymentsResponse extends ResponseEnvelope {
  @SerializedName("data")
  private List<CouponPayment> listCouponPaymentsResponseData = null;

  public ListCouponPaymentsResponse listCouponPaymentsResponseData(List<CouponPayment> listCouponPaymentsResponseData) {
    this.listCouponPaymentsResponseData = listCouponPaymentsResponseData;
    return this;
  }

  public ListCouponPaymentsResponse addListCouponPaymentsResponseDataItem(CouponPayment listCouponPaymentsResponseDataItem) {
    if (this.listCouponPaymentsResponseData == null) {
      this.listCouponPaymentsResponseData = new ArrayList<CouponPayment>();
    }
    this.listCouponPaymentsResponseData.add(listCouponPaymentsResponseDataItem);
    return this;
  }

   /**
   * Get listCouponPaymentsResponseData
   * @return listCouponPaymentsResponseData
  **/
  @Schema(description = "")
  public List<CouponPayment> getListCouponPaymentsResponseData() {
    return listCouponPaymentsResponseData;
  }

  public void setListCouponPaymentsResponseData(List<CouponPayment> listCouponPaymentsResponseData) {
    this.listCouponPaymentsResponseData = listCouponPaymentsResponseData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListCouponPaymentsResponse listCouponPaymentsResponse = (ListCouponPaymentsResponse) o;
    return Objects.equals(this.listCouponPaymentsResponseData, listCouponPaymentsResponse.listCouponPaymentsResponseData) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listCouponPaymentsResponseData, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCouponPaymentsResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    listCouponPaymentsResponseData: ").append(toIndentedString(listCouponPaymentsResponseData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
