/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import tech.dora.model.Asset;
import tech.dora.model.Metadata;
import tech.dora.model.ResponseEnvelope;
/**
 * ListAssetsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-30T15:33:45.934694888+02:00[Europe/Paris]")

public class ListAssetsResponse extends ResponseEnvelope {
  @SerializedName("data")
  private Asset listAssetsResponseData = null;

  public ListAssetsResponse listAssetsResponseData(Asset listAssetsResponseData) {
    this.listAssetsResponseData = listAssetsResponseData;
    return this;
  }

   /**
   * Get listAssetsResponseData
   * @return listAssetsResponseData
  **/
  @Schema(description = "")
  public Asset getListAssetsResponseData() {
    return listAssetsResponseData;
  }

  public void setListAssetsResponseData(Asset listAssetsResponseData) {
    this.listAssetsResponseData = listAssetsResponseData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAssetsResponse listAssetsResponse = (ListAssetsResponse) o;
    return Objects.equals(this.listAssetsResponseData, listAssetsResponse.listAssetsResponseData) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listAssetsResponseData, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAssetsResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    listAssetsResponseData: ").append(toIndentedString(listAssetsResponseData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
