/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import tech.dora.model.Metadata;
import tech.dora.model.ResponseEnvelope;
import tech.dora.model.Trade;
/**
 * ListTradeResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-09-17T17:05:29.510905976+02:00[Europe/Paris]")

public class ListTradeResponse extends ResponseEnvelope {
  @SerializedName("data")
  private List<Trade> listTradeResponseData = null;

  public ListTradeResponse listTradeResponseData(List<Trade> listTradeResponseData) {
    this.listTradeResponseData = listTradeResponseData;
    return this;
  }

  public ListTradeResponse addListTradeResponseDataItem(Trade listTradeResponseDataItem) {
    if (this.listTradeResponseData == null) {
      this.listTradeResponseData = new ArrayList<Trade>();
    }
    this.listTradeResponseData.add(listTradeResponseDataItem);
    return this;
  }

   /**
   * Get listTradeResponseData
   * @return listTradeResponseData
  **/
  @Schema(description = "")
  public List<Trade> getListTradeResponseData() {
    return listTradeResponseData;
  }

  public void setListTradeResponseData(List<Trade> listTradeResponseData) {
    this.listTradeResponseData = listTradeResponseData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListTradeResponse listTradeResponse = (ListTradeResponse) o;
    return Objects.equals(this.listTradeResponseData, listTradeResponse.listTradeResponseData) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listTradeResponseData, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListTradeResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    listTradeResponseData: ").append(toIndentedString(listTradeResponseData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
