/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets OrderBookStatus
 */
@JsonAdapter(OrderBookStatus.Adapter.class)
public enum OrderBookStatus {
  
  CLOSED("CLOSED"),
  
  OPEN("OPEN"),
  
  SUSPENDED("SUSPENDED"),
  
  TESTING("TESTING");

  private String value;

  OrderBookStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OrderBookStatus fromValue(String value) {
    for (OrderBookStatus b : OrderBookStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OrderBookStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final OrderBookStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OrderBookStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OrderBookStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    OrderBookStatus.fromValue(value);
  }
}

