/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
/**
 * OrderBookSummary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-14T20:37:48.762145180+01:00[Europe/Paris]")

public class OrderBookSummary {
  @SerializedName("order_book_id")
  private UUID orderBookId = null;

  @SerializedName("mid_price")
  private String midPrice = null;

  @SerializedName("spread")
  private String spread = null;

  @SerializedName("best_bid")
  private String bestBid = null;

  @SerializedName("best_ask")
  private String bestAsk = null;

  public OrderBookSummary orderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
    return this;
  }

   /**
   * Get orderBookId
   * @return orderBookId
  **/
  @Schema(description = "")
  public UUID getOrderBookId() {
    return orderBookId;
  }

  public void setOrderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
  }

  public OrderBookSummary midPrice(String midPrice) {
    this.midPrice = midPrice;
    return this;
  }

   /**
   * Get midPrice
   * @return midPrice
  **/
  @Schema(description = "")
  public String getMidPrice() {
    return midPrice;
  }

  public void setMidPrice(String midPrice) {
    this.midPrice = midPrice;
  }

  public OrderBookSummary spread(String spread) {
    this.spread = spread;
    return this;
  }

   /**
   * Get spread
   * @return spread
  **/
  @Schema(description = "")
  public String getSpread() {
    return spread;
  }

  public void setSpread(String spread) {
    this.spread = spread;
  }

  public OrderBookSummary bestBid(String bestBid) {
    this.bestBid = bestBid;
    return this;
  }

   /**
   * Get bestBid
   * @return bestBid
  **/
  @Schema(description = "")
  public String getBestBid() {
    return bestBid;
  }

  public void setBestBid(String bestBid) {
    this.bestBid = bestBid;
  }

  public OrderBookSummary bestAsk(String bestAsk) {
    this.bestAsk = bestAsk;
    return this;
  }

   /**
   * Get bestAsk
   * @return bestAsk
  **/
  @Schema(description = "")
  public String getBestAsk() {
    return bestAsk;
  }

  public void setBestAsk(String bestAsk) {
    this.bestAsk = bestAsk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderBookSummary orderBookSummary = (OrderBookSummary) o;
    return Objects.equals(this.orderBookId, orderBookSummary.orderBookId) &&
        Objects.equals(this.midPrice, orderBookSummary.midPrice) &&
        Objects.equals(this.spread, orderBookSummary.spread) &&
        Objects.equals(this.bestBid, orderBookSummary.bestBid) &&
        Objects.equals(this.bestAsk, orderBookSummary.bestAsk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderBookId, midPrice, spread, bestBid, bestAsk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderBookSummary {\n");
    
    sb.append("    orderBookId: ").append(toIndentedString(orderBookId)).append("\n");
    sb.append("    midPrice: ").append(toIndentedString(midPrice)).append("\n");
    sb.append("    spread: ").append(toIndentedString(spread)).append("\n");
    sb.append("    bestBid: ").append(toIndentedString(bestBid)).append("\n");
    sb.append("    bestAsk: ").append(toIndentedString(bestAsk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
