/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
/**
 * OrderBook
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-07T16:52:00.874312456+02:00[Europe/Paris]")

public class OrderBook {
  @SerializedName("order_book_id")
  private UUID orderBookId = null;

  @SerializedName("order_book_seq")
  private Integer orderBookSeq = null;

  @SerializedName("accumulated_fees_id")
  private UUID accumulatedFeesId = null;

  @SerializedName("base_quantity")
  private BigDecimal baseQuantity = null;

  @SerializedName("base_asset_id")
  private UUID baseAssetId = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("fee_factor")
  private BigDecimal feeFactor = null;

  @SerializedName("initial_assets_ratio")
  private BigDecimal initialAssetsRatio = null;

  @SerializedName("maturity_at")
  private OffsetDateTime maturityAt = null;

  @SerializedName("price_display_multiplier")
  private BigDecimal priceDisplayMultiplier = null;

  @SerializedName("quote_quantity")
  private BigDecimal quoteQuantity = null;

  @SerializedName("quote_asset_id")
  private UUID quoteAssetId = null;

  @SerializedName("shares_quantity")
  private BigDecimal sharesQuantity = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("tick_size")
  private BigDecimal tickSize = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("halted_at")
  private OffsetDateTime haltedAt = null;

  @SerializedName("terminated_at")
  private OffsetDateTime terminatedAt = null;

  @SerializedName("pool_updated_at")
  private OffsetDateTime poolUpdatedAt = null;

  @SerializedName("pool_seq")
  private Integer poolSeq = null;

  @SerializedName("shares_asset_id")
  private UUID sharesAssetId = null;

  public OrderBook orderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
    return this;
  }

   /**
   * Get orderBookId
   * @return orderBookId
  **/
  @Schema(description = "")
  public UUID getOrderBookId() {
    return orderBookId;
  }

  public void setOrderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
  }

  public OrderBook orderBookSeq(Integer orderBookSeq) {
    this.orderBookSeq = orderBookSeq;
    return this;
  }

   /**
   * Get orderBookSeq
   * @return orderBookSeq
  **/
  @Schema(description = "")
  public Integer getOrderBookSeq() {
    return orderBookSeq;
  }

  public void setOrderBookSeq(Integer orderBookSeq) {
    this.orderBookSeq = orderBookSeq;
  }

  public OrderBook accumulatedFeesId(UUID accumulatedFeesId) {
    this.accumulatedFeesId = accumulatedFeesId;
    return this;
  }

   /**
   * Get accumulatedFeesId
   * @return accumulatedFeesId
  **/
  @Schema(description = "")
  public UUID getAccumulatedFeesId() {
    return accumulatedFeesId;
  }

  public void setAccumulatedFeesId(UUID accumulatedFeesId) {
    this.accumulatedFeesId = accumulatedFeesId;
  }

  public OrderBook baseQuantity(BigDecimal baseQuantity) {
    this.baseQuantity = baseQuantity;
    return this;
  }

   /**
   * Get baseQuantity
   * @return baseQuantity
  **/
  @Schema(description = "")
  public BigDecimal getBaseQuantity() {
    return baseQuantity;
  }

  public void setBaseQuantity(BigDecimal baseQuantity) {
    this.baseQuantity = baseQuantity;
  }

  public OrderBook baseAssetId(UUID baseAssetId) {
    this.baseAssetId = baseAssetId;
    return this;
  }

   /**
   * Get baseAssetId
   * @return baseAssetId
  **/
  @Schema(description = "")
  public UUID getBaseAssetId() {
    return baseAssetId;
  }

  public void setBaseAssetId(UUID baseAssetId) {
    this.baseAssetId = baseAssetId;
  }

  public OrderBook createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public OrderBook displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OrderBook feeFactor(BigDecimal feeFactor) {
    this.feeFactor = feeFactor;
    return this;
  }

   /**
   * Get feeFactor
   * @return feeFactor
  **/
  @Schema(description = "")
  public BigDecimal getFeeFactor() {
    return feeFactor;
  }

  public void setFeeFactor(BigDecimal feeFactor) {
    this.feeFactor = feeFactor;
  }

  public OrderBook initialAssetsRatio(BigDecimal initialAssetsRatio) {
    this.initialAssetsRatio = initialAssetsRatio;
    return this;
  }

   /**
   * Get initialAssetsRatio
   * @return initialAssetsRatio
  **/
  @Schema(description = "")
  public BigDecimal getInitialAssetsRatio() {
    return initialAssetsRatio;
  }

  public void setInitialAssetsRatio(BigDecimal initialAssetsRatio) {
    this.initialAssetsRatio = initialAssetsRatio;
  }

  public OrderBook maturityAt(OffsetDateTime maturityAt) {
    this.maturityAt = maturityAt;
    return this;
  }

   /**
   * Get maturityAt
   * @return maturityAt
  **/
  @Schema(description = "")
  public OffsetDateTime getMaturityAt() {
    return maturityAt;
  }

  public void setMaturityAt(OffsetDateTime maturityAt) {
    this.maturityAt = maturityAt;
  }

  public OrderBook priceDisplayMultiplier(BigDecimal priceDisplayMultiplier) {
    this.priceDisplayMultiplier = priceDisplayMultiplier;
    return this;
  }

   /**
   * Get priceDisplayMultiplier
   * @return priceDisplayMultiplier
  **/
  @Schema(description = "")
  public BigDecimal getPriceDisplayMultiplier() {
    return priceDisplayMultiplier;
  }

  public void setPriceDisplayMultiplier(BigDecimal priceDisplayMultiplier) {
    this.priceDisplayMultiplier = priceDisplayMultiplier;
  }

  public OrderBook quoteQuantity(BigDecimal quoteQuantity) {
    this.quoteQuantity = quoteQuantity;
    return this;
  }

   /**
   * Get quoteQuantity
   * @return quoteQuantity
  **/
  @Schema(description = "")
  public BigDecimal getQuoteQuantity() {
    return quoteQuantity;
  }

  public void setQuoteQuantity(BigDecimal quoteQuantity) {
    this.quoteQuantity = quoteQuantity;
  }

  public OrderBook quoteAssetId(UUID quoteAssetId) {
    this.quoteAssetId = quoteAssetId;
    return this;
  }

   /**
   * Get quoteAssetId
   * @return quoteAssetId
  **/
  @Schema(description = "")
  public UUID getQuoteAssetId() {
    return quoteAssetId;
  }

  public void setQuoteAssetId(UUID quoteAssetId) {
    this.quoteAssetId = quoteAssetId;
  }

  public OrderBook sharesQuantity(BigDecimal sharesQuantity) {
    this.sharesQuantity = sharesQuantity;
    return this;
  }

   /**
   * Get sharesQuantity
   * @return sharesQuantity
  **/
  @Schema(description = "")
  public BigDecimal getSharesQuantity() {
    return sharesQuantity;
  }

  public void setSharesQuantity(BigDecimal sharesQuantity) {
    this.sharesQuantity = sharesQuantity;
  }

  public OrderBook status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public OrderBook tickSize(BigDecimal tickSize) {
    this.tickSize = tickSize;
    return this;
  }

   /**
   * Get tickSize
   * @return tickSize
  **/
  @Schema(description = "")
  public BigDecimal getTickSize() {
    return tickSize;
  }

  public void setTickSize(BigDecimal tickSize) {
    this.tickSize = tickSize;
  }

  public OrderBook updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public OrderBook haltedAt(OffsetDateTime haltedAt) {
    this.haltedAt = haltedAt;
    return this;
  }

   /**
   * Get haltedAt
   * @return haltedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getHaltedAt() {
    return haltedAt;
  }

  public void setHaltedAt(OffsetDateTime haltedAt) {
    this.haltedAt = haltedAt;
  }

  public OrderBook terminatedAt(OffsetDateTime terminatedAt) {
    this.terminatedAt = terminatedAt;
    return this;
  }

   /**
   * Get terminatedAt
   * @return terminatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getTerminatedAt() {
    return terminatedAt;
  }

  public void setTerminatedAt(OffsetDateTime terminatedAt) {
    this.terminatedAt = terminatedAt;
  }

  public OrderBook poolUpdatedAt(OffsetDateTime poolUpdatedAt) {
    this.poolUpdatedAt = poolUpdatedAt;
    return this;
  }

   /**
   * Get poolUpdatedAt
   * @return poolUpdatedAt
  **/
  @Schema(description = "")
  public OffsetDateTime getPoolUpdatedAt() {
    return poolUpdatedAt;
  }

  public void setPoolUpdatedAt(OffsetDateTime poolUpdatedAt) {
    this.poolUpdatedAt = poolUpdatedAt;
  }

  public OrderBook poolSeq(Integer poolSeq) {
    this.poolSeq = poolSeq;
    return this;
  }

   /**
   * Get poolSeq
   * @return poolSeq
  **/
  @Schema(description = "")
  public Integer getPoolSeq() {
    return poolSeq;
  }

  public void setPoolSeq(Integer poolSeq) {
    this.poolSeq = poolSeq;
  }

  public OrderBook sharesAssetId(UUID sharesAssetId) {
    this.sharesAssetId = sharesAssetId;
    return this;
  }

   /**
   * Get sharesAssetId
   * @return sharesAssetId
  **/
  @Schema(description = "")
  public UUID getSharesAssetId() {
    return sharesAssetId;
  }

  public void setSharesAssetId(UUID sharesAssetId) {
    this.sharesAssetId = sharesAssetId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderBook orderBook = (OrderBook) o;
    return Objects.equals(this.orderBookId, orderBook.orderBookId) &&
        Objects.equals(this.orderBookSeq, orderBook.orderBookSeq) &&
        Objects.equals(this.accumulatedFeesId, orderBook.accumulatedFeesId) &&
        Objects.equals(this.baseQuantity, orderBook.baseQuantity) &&
        Objects.equals(this.baseAssetId, orderBook.baseAssetId) &&
        Objects.equals(this.createdAt, orderBook.createdAt) &&
        Objects.equals(this.displayName, orderBook.displayName) &&
        Objects.equals(this.feeFactor, orderBook.feeFactor) &&
        Objects.equals(this.initialAssetsRatio, orderBook.initialAssetsRatio) &&
        Objects.equals(this.maturityAt, orderBook.maturityAt) &&
        Objects.equals(this.priceDisplayMultiplier, orderBook.priceDisplayMultiplier) &&
        Objects.equals(this.quoteQuantity, orderBook.quoteQuantity) &&
        Objects.equals(this.quoteAssetId, orderBook.quoteAssetId) &&
        Objects.equals(this.sharesQuantity, orderBook.sharesQuantity) &&
        Objects.equals(this.status, orderBook.status) &&
        Objects.equals(this.tickSize, orderBook.tickSize) &&
        Objects.equals(this.updatedAt, orderBook.updatedAt) &&
        Objects.equals(this.haltedAt, orderBook.haltedAt) &&
        Objects.equals(this.terminatedAt, orderBook.terminatedAt) &&
        Objects.equals(this.poolUpdatedAt, orderBook.poolUpdatedAt) &&
        Objects.equals(this.poolSeq, orderBook.poolSeq) &&
        Objects.equals(this.sharesAssetId, orderBook.sharesAssetId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderBookId, orderBookSeq, accumulatedFeesId, baseQuantity, baseAssetId, createdAt, displayName, feeFactor, initialAssetsRatio, maturityAt, priceDisplayMultiplier, quoteQuantity, quoteAssetId, sharesQuantity, status, tickSize, updatedAt, haltedAt, terminatedAt, poolUpdatedAt, poolSeq, sharesAssetId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderBook {\n");
    
    sb.append("    orderBookId: ").append(toIndentedString(orderBookId)).append("\n");
    sb.append("    orderBookSeq: ").append(toIndentedString(orderBookSeq)).append("\n");
    sb.append("    accumulatedFeesId: ").append(toIndentedString(accumulatedFeesId)).append("\n");
    sb.append("    baseQuantity: ").append(toIndentedString(baseQuantity)).append("\n");
    sb.append("    baseAssetId: ").append(toIndentedString(baseAssetId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    feeFactor: ").append(toIndentedString(feeFactor)).append("\n");
    sb.append("    initialAssetsRatio: ").append(toIndentedString(initialAssetsRatio)).append("\n");
    sb.append("    maturityAt: ").append(toIndentedString(maturityAt)).append("\n");
    sb.append("    priceDisplayMultiplier: ").append(toIndentedString(priceDisplayMultiplier)).append("\n");
    sb.append("    quoteQuantity: ").append(toIndentedString(quoteQuantity)).append("\n");
    sb.append("    quoteAssetId: ").append(toIndentedString(quoteAssetId)).append("\n");
    sb.append("    sharesQuantity: ").append(toIndentedString(sharesQuantity)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tickSize: ").append(toIndentedString(tickSize)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    haltedAt: ").append(toIndentedString(haltedAt)).append("\n");
    sb.append("    terminatedAt: ").append(toIndentedString(terminatedAt)).append("\n");
    sb.append("    poolUpdatedAt: ").append(toIndentedString(poolUpdatedAt)).append("\n");
    sb.append("    poolSeq: ").append(toIndentedString(poolSeq)).append("\n");
    sb.append("    sharesAssetId: ").append(toIndentedString(sharesAssetId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
