/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import tech.dora.model.AssetKind;
import tech.dora.model.Margin;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import tech.dora.JSON;

/**
 * PLAsset
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-02T17:13:50.947925667+02:00[Europe/Paris]", comments = "Generator version: 7.17.0")
public class PLAsset {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  @javax.annotation.Nonnull
  private AssetKind kind;

  public static final String SERIALIZED_NAME_SYMBOL = "symbol";
  @SerializedName(SERIALIZED_NAME_SYMBOL)
  @javax.annotation.Nonnull
  private String symbol;

  /**
   * The side of the position (LONG or SHORT)
   */
  @JsonAdapter(SideEnum.Adapter.class)
  public enum SideEnum {
    LONG("LONG"),
    
    SHORT("SHORT");

    private String value;

    SideEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SideEnum fromValue(String value) {
      for (SideEnum b : SideEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SideEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SideEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SideEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SideEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SideEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SIDE = "side";
  @SerializedName(SERIALIZED_NAME_SIDE)
  @javax.annotation.Nonnull
  private SideEnum side;

  public static final String SERIALIZED_NAME_AVG_ENTRY_PRICE = "avg_entry_price";
  @SerializedName(SERIALIZED_NAME_AVG_ENTRY_PRICE)
  @javax.annotation.Nonnull
  private String avgEntryPrice;

  public static final String SERIALIZED_NAME_MARK_PRICE = "mark_price";
  @SerializedName(SERIALIZED_NAME_MARK_PRICE)
  @javax.annotation.Nonnull
  private String markPrice;

  public static final String SERIALIZED_NAME_LIQUIDATION_PRICE = "liquidation_price";
  @SerializedName(SERIALIZED_NAME_LIQUIDATION_PRICE)
  @javax.annotation.Nonnull
  private String liquidationPrice;

  public static final String SERIALIZED_NAME_AVAILABLE = "available";
  @SerializedName(SERIALIZED_NAME_AVAILABLE)
  @javax.annotation.Nonnull
  private String available;

  public static final String SERIALIZED_NAME_BORROWED = "borrowed";
  @SerializedName(SERIALIZED_NAME_BORROWED)
  @javax.annotation.Nonnull
  private String borrowed;

  public static final String SERIALIZED_NAME_MARGIN = "margin";
  @SerializedName(SERIALIZED_NAME_MARGIN)
  @javax.annotation.Nonnull
  private Margin margin;

  public static final String SERIALIZED_NAME_UNREALIZED_PL = "unrealized_pl";
  @SerializedName(SERIALIZED_NAME_UNREALIZED_PL)
  @javax.annotation.Nonnull
  private String unrealizedPl;

  public static final String SERIALIZED_NAME_LEVERAGE_LIMIT = "leverage_limit";
  @SerializedName(SERIALIZED_NAME_LEVERAGE_LIMIT)
  @javax.annotation.Nonnull
  private String leverageLimit;

  public static final String SERIALIZED_NAME_TP = "tp";
  @SerializedName(SERIALIZED_NAME_TP)
  @javax.annotation.Nullable
  private String tp;

  public static final String SERIALIZED_NAME_SL = "sl";
  @SerializedName(SERIALIZED_NAME_SL)
  @javax.annotation.Nullable
  private String sl;

  public static final String SERIALIZED_NAME_INITIAL_CAPITAL = "initial_capital";
  @SerializedName(SERIALIZED_NAME_INITIAL_CAPITAL)
  @javax.annotation.Nonnull
  private String initialCapital;

  public static final String SERIALIZED_NAME_IMPENDING_BORROWS = "impending_borrows";
  @SerializedName(SERIALIZED_NAME_IMPENDING_BORROWS)
  @javax.annotation.Nullable
  private String impendingBorrows;

  public static final String SERIALIZED_NAME_LOCKED = "locked";
  @SerializedName(SERIALIZED_NAME_LOCKED)
  @javax.annotation.Nonnull
  private String locked;

  public static final String SERIALIZED_NAME_UNUSED_COLLATERAL = "unused_collateral";
  @SerializedName(SERIALIZED_NAME_UNUSED_COLLATERAL)
  @javax.annotation.Nonnull
  private String unusedCollateral;

  public PLAsset() {
  }

  public PLAsset id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the asset
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public PLAsset kind(@javax.annotation.Nonnull AssetKind kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   * @return kind
   */
  @javax.annotation.Nonnull
  public AssetKind getKind() {
    return kind;
  }

  public void setKind(@javax.annotation.Nonnull AssetKind kind) {
    this.kind = kind;
  }


  public PLAsset symbol(@javax.annotation.Nonnull String symbol) {
    this.symbol = symbol;
    return this;
  }

  /**
   * The symbol of the asset
   * @return symbol
   */
  @javax.annotation.Nonnull
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(@javax.annotation.Nonnull String symbol) {
    this.symbol = symbol;
  }


  public PLAsset side(@javax.annotation.Nonnull SideEnum side) {
    this.side = side;
    return this;
  }

  /**
   * The side of the position (LONG or SHORT)
   * @return side
   */
  @javax.annotation.Nonnull
  public SideEnum getSide() {
    return side;
  }

  public void setSide(@javax.annotation.Nonnull SideEnum side) {
    this.side = side;
  }


  public PLAsset avgEntryPrice(@javax.annotation.Nonnull String avgEntryPrice) {
    this.avgEntryPrice = avgEntryPrice;
    return this;
  }

  /**
   * The average entry price of the position
   * @return avgEntryPrice
   */
  @javax.annotation.Nonnull
  public String getAvgEntryPrice() {
    return avgEntryPrice;
  }

  public void setAvgEntryPrice(@javax.annotation.Nonnull String avgEntryPrice) {
    this.avgEntryPrice = avgEntryPrice;
  }


  public PLAsset markPrice(@javax.annotation.Nonnull String markPrice) {
    this.markPrice = markPrice;
    return this;
  }

  /**
   * The current mark price for the asset to calculate daily PL. This is usually the close price of the previous day
   * @return markPrice
   */
  @javax.annotation.Nonnull
  public String getMarkPrice() {
    return markPrice;
  }

  public void setMarkPrice(@javax.annotation.Nonnull String markPrice) {
    this.markPrice = markPrice;
  }


  public PLAsset liquidationPrice(@javax.annotation.Nonnull String liquidationPrice) {
    this.liquidationPrice = liquidationPrice;
    return this;
  }

  /**
   * The liquidation price of the position
   * @return liquidationPrice
   */
  @javax.annotation.Nonnull
  public String getLiquidationPrice() {
    return liquidationPrice;
  }

  public void setLiquidationPrice(@javax.annotation.Nonnull String liquidationPrice) {
    this.liquidationPrice = liquidationPrice;
  }


  public PLAsset available(@javax.annotation.Nonnull String available) {
    this.available = available;
    return this;
  }

  /**
   * The available quantity in units of the asset
   * @return available
   */
  @javax.annotation.Nonnull
  public String getAvailable() {
    return available;
  }

  public void setAvailable(@javax.annotation.Nonnull String available) {
    this.available = available;
  }


  public PLAsset borrowed(@javax.annotation.Nonnull String borrowed) {
    this.borrowed = borrowed;
    return this;
  }

  /**
   * The borrowed quantity in units of the asset
   * @return borrowed
   */
  @javax.annotation.Nonnull
  public String getBorrowed() {
    return borrowed;
  }

  public void setBorrowed(@javax.annotation.Nonnull String borrowed) {
    this.borrowed = borrowed;
  }


  public PLAsset margin(@javax.annotation.Nonnull Margin margin) {
    this.margin = margin;
    return this;
  }

  /**
   * Get margin
   * @return margin
   */
  @javax.annotation.Nonnull
  public Margin getMargin() {
    return margin;
  }

  public void setMargin(@javax.annotation.Nonnull Margin margin) {
    this.margin = margin;
  }


  public PLAsset unrealizedPl(@javax.annotation.Nonnull String unrealizedPl) {
    this.unrealizedPl = unrealizedPl;
    return this;
  }

  /**
   * The unrealized profit or loss of the position
   * @return unrealizedPl
   */
  @javax.annotation.Nonnull
  public String getUnrealizedPl() {
    return unrealizedPl;
  }

  public void setUnrealizedPl(@javax.annotation.Nonnull String unrealizedPl) {
    this.unrealizedPl = unrealizedPl;
  }


  public PLAsset leverageLimit(@javax.annotation.Nonnull String leverageLimit) {
    this.leverageLimit = leverageLimit;
    return this;
  }

  /**
   * The leverage limit for the position
   * @return leverageLimit
   */
  @javax.annotation.Nonnull
  public String getLeverageLimit() {
    return leverageLimit;
  }

  public void setLeverageLimit(@javax.annotation.Nonnull String leverageLimit) {
    this.leverageLimit = leverageLimit;
  }


  public PLAsset tp(@javax.annotation.Nullable String tp) {
    this.tp = tp;
    return this;
  }

  /**
   * The take profit price set for the position, if any
   * @return tp
   */
  @javax.annotation.Nullable
  public String getTp() {
    return tp;
  }

  public void setTp(@javax.annotation.Nullable String tp) {
    this.tp = tp;
  }


  public PLAsset sl(@javax.annotation.Nullable String sl) {
    this.sl = sl;
    return this;
  }

  /**
   * The stop loss price set for the position, if any
   * @return sl
   */
  @javax.annotation.Nullable
  public String getSl() {
    return sl;
  }

  public void setSl(@javax.annotation.Nullable String sl) {
    this.sl = sl;
  }


  public PLAsset initialCapital(@javax.annotation.Nonnull String initialCapital) {
    this.initialCapital = initialCapital;
    return this;
  }

  /**
   * The initial capital of the position
   * @return initialCapital
   */
  @javax.annotation.Nonnull
  public String getInitialCapital() {
    return initialCapital;
  }

  public void setInitialCapital(@javax.annotation.Nonnull String initialCapital) {
    this.initialCapital = initialCapital;
  }


  public PLAsset impendingBorrows(@javax.annotation.Nullable String impendingBorrows) {
    this.impendingBorrows = impendingBorrows;
    return this;
  }

  /**
   * The impending borrows of the position
   * @return impendingBorrows
   */
  @javax.annotation.Nullable
  public String getImpendingBorrows() {
    return impendingBorrows;
  }

  public void setImpendingBorrows(@javax.annotation.Nullable String impendingBorrows) {
    this.impendingBorrows = impendingBorrows;
  }


  public PLAsset locked(@javax.annotation.Nonnull String locked) {
    this.locked = locked;
    return this;
  }

  /**
   * The locked amount of the position
   * @return locked
   */
  @javax.annotation.Nonnull
  public String getLocked() {
    return locked;
  }

  public void setLocked(@javax.annotation.Nonnull String locked) {
    this.locked = locked;
  }


  public PLAsset unusedCollateral(@javax.annotation.Nonnull String unusedCollateral) {
    this.unusedCollateral = unusedCollateral;
    return this;
  }

  /**
   * The unused collateral of the position
   * @return unusedCollateral
   */
  @javax.annotation.Nonnull
  public String getUnusedCollateral() {
    return unusedCollateral;
  }

  public void setUnusedCollateral(@javax.annotation.Nonnull String unusedCollateral) {
    this.unusedCollateral = unusedCollateral;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PLAsset plAsset = (PLAsset) o;
    return Objects.equals(this.id, plAsset.id) &&
        Objects.equals(this.kind, plAsset.kind) &&
        Objects.equals(this.symbol, plAsset.symbol) &&
        Objects.equals(this.side, plAsset.side) &&
        Objects.equals(this.avgEntryPrice, plAsset.avgEntryPrice) &&
        Objects.equals(this.markPrice, plAsset.markPrice) &&
        Objects.equals(this.liquidationPrice, plAsset.liquidationPrice) &&
        Objects.equals(this.available, plAsset.available) &&
        Objects.equals(this.borrowed, plAsset.borrowed) &&
        Objects.equals(this.margin, plAsset.margin) &&
        Objects.equals(this.unrealizedPl, plAsset.unrealizedPl) &&
        Objects.equals(this.leverageLimit, plAsset.leverageLimit) &&
        Objects.equals(this.tp, plAsset.tp) &&
        Objects.equals(this.sl, plAsset.sl) &&
        Objects.equals(this.initialCapital, plAsset.initialCapital) &&
        Objects.equals(this.impendingBorrows, plAsset.impendingBorrows) &&
        Objects.equals(this.locked, plAsset.locked) &&
        Objects.equals(this.unusedCollateral, plAsset.unusedCollateral);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, kind, symbol, side, avgEntryPrice, markPrice, liquidationPrice, available, borrowed, margin, unrealizedPl, leverageLimit, tp, sl, initialCapital, impendingBorrows, locked, unusedCollateral);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PLAsset {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    avgEntryPrice: ").append(toIndentedString(avgEntryPrice)).append("\n");
    sb.append("    markPrice: ").append(toIndentedString(markPrice)).append("\n");
    sb.append("    liquidationPrice: ").append(toIndentedString(liquidationPrice)).append("\n");
    sb.append("    available: ").append(toIndentedString(available)).append("\n");
    sb.append("    borrowed: ").append(toIndentedString(borrowed)).append("\n");
    sb.append("    margin: ").append(toIndentedString(margin)).append("\n");
    sb.append("    unrealizedPl: ").append(toIndentedString(unrealizedPl)).append("\n");
    sb.append("    leverageLimit: ").append(toIndentedString(leverageLimit)).append("\n");
    sb.append("    tp: ").append(toIndentedString(tp)).append("\n");
    sb.append("    sl: ").append(toIndentedString(sl)).append("\n");
    sb.append("    initialCapital: ").append(toIndentedString(initialCapital)).append("\n");
    sb.append("    impendingBorrows: ").append(toIndentedString(impendingBorrows)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    unusedCollateral: ").append(toIndentedString(unusedCollateral)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "kind", "symbol", "side", "avg_entry_price", "mark_price", "liquidation_price", "available", "borrowed", "margin", "unrealized_pl", "leverage_limit", "tp", "sl", "initial_capital", "impending_borrows", "locked", "unused_collateral"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "kind", "symbol", "side", "avg_entry_price", "mark_price", "liquidation_price", "available", "borrowed", "margin", "unrealized_pl", "leverage_limit", "initial_capital", "locked", "unused_collateral"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PLAsset
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PLAsset.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in PLAsset is not found in the empty JSON string", PLAsset.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PLAsset.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PLAsset` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PLAsset.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // validate the required field `kind`
      AssetKind.validateJsonElement(jsonObj.get("kind"));
      if (!jsonObj.get("symbol").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `symbol` to be a primitive type in the JSON string but got `%s`", jsonObj.get("symbol").toString()));
      }
      if (!jsonObj.get("side").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `side` to be a primitive type in the JSON string but got `%s`", jsonObj.get("side").toString()));
      }
      // validate the required field `side`
      SideEnum.validateJsonElement(jsonObj.get("side"));
      if (!jsonObj.get("avg_entry_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `avg_entry_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("avg_entry_price").toString()));
      }
      if (!jsonObj.get("mark_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `mark_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mark_price").toString()));
      }
      if (!jsonObj.get("liquidation_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `liquidation_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("liquidation_price").toString()));
      }
      if (!jsonObj.get("available").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `available` to be a primitive type in the JSON string but got `%s`", jsonObj.get("available").toString()));
      }
      if (!jsonObj.get("borrowed").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `borrowed` to be a primitive type in the JSON string but got `%s`", jsonObj.get("borrowed").toString()));
      }
      // validate the required field `margin`
      Margin.validateJsonElement(jsonObj.get("margin"));
      if (!jsonObj.get("unrealized_pl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `unrealized_pl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unrealized_pl").toString()));
      }
      if (!jsonObj.get("leverage_limit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `leverage_limit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("leverage_limit").toString()));
      }
      if ((jsonObj.get("tp") != null && !jsonObj.get("tp").isJsonNull()) && !jsonObj.get("tp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `tp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tp").toString()));
      }
      if ((jsonObj.get("sl") != null && !jsonObj.get("sl").isJsonNull()) && !jsonObj.get("sl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sl").toString()));
      }
      if (!jsonObj.get("initial_capital").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `initial_capital` to be a primitive type in the JSON string but got `%s`", jsonObj.get("initial_capital").toString()));
      }
      if ((jsonObj.get("impending_borrows") != null && !jsonObj.get("impending_borrows").isJsonNull()) && !jsonObj.get("impending_borrows").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `impending_borrows` to be a primitive type in the JSON string but got `%s`", jsonObj.get("impending_borrows").toString()));
      }
      if (!jsonObj.get("locked").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `locked` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locked").toString()));
      }
      if (!jsonObj.get("unused_collateral").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `unused_collateral` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unused_collateral").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PLAsset.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PLAsset' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PLAsset> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PLAsset.class));

       return (TypeAdapter<T>) new TypeAdapter<PLAsset>() {
           @Override
           public void write(JsonWriter out, PLAsset value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PLAsset read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PLAsset given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PLAsset
   * @throws IOException if the JSON string is invalid with respect to PLAsset
   */
  public static PLAsset fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PLAsset.class);
  }

  /**
   * Convert an instance of PLAsset to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

