/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import tech.dora.model.Metadata;
import tech.dora.model.ResponseEnvelope;
/**
 * PoolNotFoundError
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-31T15:51:13.749482230+02:00[Europe/Paris]")

public class PoolNotFoundError extends ResponseEnvelope {
  @SerializedName("error")
  private String poolNotFoundErrorError = null;

  public PoolNotFoundError poolNotFoundErrorError(String poolNotFoundErrorError) {
    this.poolNotFoundErrorError = poolNotFoundErrorError;
    return this;
  }

   /**
   * Get poolNotFoundErrorError
   * @return poolNotFoundErrorError
  **/
  @Schema(description = "")
  public String getPoolNotFoundErrorError() {
    return poolNotFoundErrorError;
  }

  public void setPoolNotFoundErrorError(String poolNotFoundErrorError) {
    this.poolNotFoundErrorError = poolNotFoundErrorError;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoolNotFoundError poolNotFoundError = (PoolNotFoundError) o;
    return Objects.equals(this.poolNotFoundErrorError, poolNotFoundError.poolNotFoundErrorError) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(poolNotFoundErrorError, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoolNotFoundError {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    poolNotFoundErrorError: ").append(toIndentedString(poolNotFoundErrorError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
