/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PositionType
 */
@JsonAdapter(PositionType.Adapter.class)
public enum PositionType {
  
  OWNED("Owned"),
  
  LOCKED("Locked"),
  
  SUPPLIED("Supplied"),
  
  STABLECOIN_EQUIVALENTS("Stablecoin Equivalents"),
  
  INACTIVE("Inactive"),
  
  INTEREST_SOURCES("Interest Sources");

  private String value;

  PositionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PositionType fromValue(String value) {
    for (PositionType b : PositionType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PositionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PositionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PositionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PositionType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PositionType.fromValue(value);
  }
}

