/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import tech.dora.model.PromoLinkStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tech.dora.JSON;

/**
 * PromoLinkAdmin
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-18T18:29:04.763912996+02:00[Europe/Paris]", comments = "Generator version: 7.23.0")
public class PromoLinkAdmin {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_TOKEN_PREFIX = "token_prefix";
  @SerializedName(SERIALIZED_NAME_TOKEN_PREFIX)
  @javax.annotation.Nonnull
  private String tokenPrefix;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private URI url;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private PromoLinkStatus status;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_CLAIMED_AT = "claimed_at";
  @SerializedName(SERIALIZED_NAME_CLAIMED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime claimedAt;

  public static final String SERIALIZED_NAME_CLAIMED_EMAIL = "claimed_email";
  @SerializedName(SERIALIZED_NAME_CLAIMED_EMAIL)
  @javax.annotation.Nullable
  private String claimedEmail;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private UUID userId;

  public PromoLinkAdmin() {
  }

  public PromoLinkAdmin id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public PromoLinkAdmin tokenPrefix(@javax.annotation.Nonnull String tokenPrefix) {
    this.tokenPrefix = tokenPrefix;
    return this;
  }

  /**
   * Get tokenPrefix
   * @return tokenPrefix
   */
  @javax.annotation.Nonnull
  public String getTokenPrefix() {
    return tokenPrefix;
  }

  public void setTokenPrefix(@javax.annotation.Nonnull String tokenPrefix) {
    this.tokenPrefix = tokenPrefix;
  }


  public PromoLinkAdmin url(@javax.annotation.Nullable URI url) {
    this.url = url;
    return this;
  }

  /**
   * Only present when reveal&#x3D;true. Private; do not log or cache.
   * @return url
   */
  @javax.annotation.Nullable
  public URI getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable URI url) {
    this.url = url;
  }


  public PromoLinkAdmin status(@javax.annotation.Nonnull PromoLinkStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public PromoLinkStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull PromoLinkStatus status) {
    this.status = status;
  }


  public PromoLinkAdmin expiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public PromoLinkAdmin claimedAt(@javax.annotation.Nullable OffsetDateTime claimedAt) {
    this.claimedAt = claimedAt;
    return this;
  }

  /**
   * Get claimedAt
   * @return claimedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getClaimedAt() {
    return claimedAt;
  }

  public void setClaimedAt(@javax.annotation.Nullable OffsetDateTime claimedAt) {
    this.claimedAt = claimedAt;
  }


  public PromoLinkAdmin claimedEmail(@javax.annotation.Nullable String claimedEmail) {
    this.claimedEmail = claimedEmail;
    return this;
  }

  /**
   * Masked as the first character, three asterisks, and domain.
   * @return claimedEmail
   */
  @javax.annotation.Nullable
  public String getClaimedEmail() {
    return claimedEmail;
  }

  public void setClaimedEmail(@javax.annotation.Nullable String claimedEmail) {
    this.claimedEmail = claimedEmail;
  }


  public PromoLinkAdmin userId(@javax.annotation.Nullable UUID userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable UUID userId) {
    this.userId = userId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromoLinkAdmin promoLinkAdmin = (PromoLinkAdmin) o;
    return Objects.equals(this.id, promoLinkAdmin.id) &&
        Objects.equals(this.tokenPrefix, promoLinkAdmin.tokenPrefix) &&
        Objects.equals(this.url, promoLinkAdmin.url) &&
        Objects.equals(this.status, promoLinkAdmin.status) &&
        Objects.equals(this.expiresAt, promoLinkAdmin.expiresAt) &&
        Objects.equals(this.claimedAt, promoLinkAdmin.claimedAt) &&
        Objects.equals(this.claimedEmail, promoLinkAdmin.claimedEmail) &&
        Objects.equals(this.userId, promoLinkAdmin.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tokenPrefix, url, status, expiresAt, claimedAt, claimedEmail, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromoLinkAdmin {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tokenPrefix: ").append(toIndentedString(tokenPrefix)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    claimedAt: ").append(toIndentedString(claimedAt)).append("\n");
    sb.append("    claimedEmail: ").append(toIndentedString(claimedEmail)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "token_prefix", "url", "status", "expires_at", "claimed_at", "claimed_email", "user_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "token_prefix", "status", "expires_at"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PromoLinkAdmin
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PromoLinkAdmin.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PromoLinkAdmin is not found in the empty JSON string", PromoLinkAdmin.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PromoLinkAdmin.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PromoLinkAdmin` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PromoLinkAdmin.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("token_prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `token_prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token_prefix").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      // validate the required field `status`
      PromoLinkStatus.validateJsonElement(jsonObj.get("status"));
      if ((jsonObj.get("claimed_email") != null && !jsonObj.get("claimed_email").isJsonNull()) && !jsonObj.get("claimed_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `claimed_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("claimed_email").toString()));
      }
      if ((jsonObj.get("user_id") != null && !jsonObj.get("user_id").isJsonNull()) && !jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PromoLinkAdmin.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PromoLinkAdmin' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PromoLinkAdmin> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PromoLinkAdmin.class));

       return (TypeAdapter<T>) new TypeAdapter<PromoLinkAdmin>() {
           @Override
           public void write(JsonWriter out, PromoLinkAdmin value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PromoLinkAdmin read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PromoLinkAdmin given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PromoLinkAdmin
   * @throws IOException if the JSON string is invalid with respect to PromoLinkAdmin
   */
  public static PromoLinkAdmin fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PromoLinkAdmin.class);
  }

  /**
   * Convert an instance of PromoLinkAdmin to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

