/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * StreamAssetsResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-01-07T14:32:58.731305576+01:00[Europe/Paris]")

public class StreamAssetsResponse {
  @SerializedName("stream_assets_entries")
  private Object streamAssetsEntries = null;

  public StreamAssetsResponse streamAssetsEntries(Object streamAssetsEntries) {
    this.streamAssetsEntries = streamAssetsEntries;
    return this;
  }

   /**
   * Get streamAssetsEntries
   * @return streamAssetsEntries
  **/
  @Schema(description = "")
  public Object getStreamAssetsEntries() {
    return streamAssetsEntries;
  }

  public void setStreamAssetsEntries(Object streamAssetsEntries) {
    this.streamAssetsEntries = streamAssetsEntries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamAssetsResponse streamAssetsResponse = (StreamAssetsResponse) o;
    return Objects.equals(this.streamAssetsEntries, streamAssetsResponse.streamAssetsEntries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(streamAssetsEntries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamAssetsResponse {\n");
    
    sb.append("    streamAssetsEntries: ").append(toIndentedString(streamAssetsEntries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
