/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
/**
 * Trade
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-30T15:33:45.934694888+02:00[Europe/Paris]")

public class Trade {
  @SerializedName("transaction_id")
  private UUID transactionId = null;

  @SerializedName("user_id")
  private UUID userId = null;

  @SerializedName("order_id")
  private UUID orderId = null;

  @SerializedName("order_seq")
  private Integer orderSeq = null;

  @SerializedName("order_book_id")
  private UUID orderBookId = null;

  @SerializedName("asset_id")
  private UUID assetId = null;

  @SerializedName("quantity")
  private String quantity = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("fee_asset_id")
  private UUID feeAssetId = null;

  @SerializedName("fee_quantity")
  private String feeQuantity = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  public Trade transactionId(UUID transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @Schema(description = "")
  public UUID getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(UUID transactionId) {
    this.transactionId = transactionId;
  }

  public Trade userId(UUID userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  public Trade orderId(UUID orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(description = "")
  public UUID getOrderId() {
    return orderId;
  }

  public void setOrderId(UUID orderId) {
    this.orderId = orderId;
  }

  public Trade orderSeq(Integer orderSeq) {
    this.orderSeq = orderSeq;
    return this;
  }

   /**
   * Get orderSeq
   * @return orderSeq
  **/
  @Schema(description = "")
  public Integer getOrderSeq() {
    return orderSeq;
  }

  public void setOrderSeq(Integer orderSeq) {
    this.orderSeq = orderSeq;
  }

  public Trade orderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
    return this;
  }

   /**
   * Get orderBookId
   * @return orderBookId
  **/
  @Schema(description = "")
  public UUID getOrderBookId() {
    return orderBookId;
  }

  public void setOrderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
  }

  public Trade assetId(UUID assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Get assetId
   * @return assetId
  **/
  @Schema(description = "")
  public UUID getAssetId() {
    return assetId;
  }

  public void setAssetId(UUID assetId) {
    this.assetId = assetId;
  }

  public Trade quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }

  public Trade price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public Trade feeAssetId(UUID feeAssetId) {
    this.feeAssetId = feeAssetId;
    return this;
  }

   /**
   * Get feeAssetId
   * @return feeAssetId
  **/
  @Schema(description = "")
  public UUID getFeeAssetId() {
    return feeAssetId;
  }

  public void setFeeAssetId(UUID feeAssetId) {
    this.feeAssetId = feeAssetId;
  }

  public Trade feeQuantity(String feeQuantity) {
    this.feeQuantity = feeQuantity;
    return this;
  }

   /**
   * Get feeQuantity
   * @return feeQuantity
  **/
  @Schema(description = "")
  public String getFeeQuantity() {
    return feeQuantity;
  }

  public void setFeeQuantity(String feeQuantity) {
    this.feeQuantity = feeQuantity;
  }

  public Trade createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trade trade = (Trade) o;
    return Objects.equals(this.transactionId, trade.transactionId) &&
        Objects.equals(this.userId, trade.userId) &&
        Objects.equals(this.orderId, trade.orderId) &&
        Objects.equals(this.orderSeq, trade.orderSeq) &&
        Objects.equals(this.orderBookId, trade.orderBookId) &&
        Objects.equals(this.assetId, trade.assetId) &&
        Objects.equals(this.quantity, trade.quantity) &&
        Objects.equals(this.price, trade.price) &&
        Objects.equals(this.feeAssetId, trade.feeAssetId) &&
        Objects.equals(this.feeQuantity, trade.feeQuantity) &&
        Objects.equals(this.createdAt, trade.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, userId, orderId, orderSeq, orderBookId, assetId, quantity, price, feeAssetId, feeQuantity, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trade {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderSeq: ").append(toIndentedString(orderSeq)).append("\n");
    sb.append("    orderBookId: ").append(toIndentedString(orderBookId)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    feeAssetId: ").append(toIndentedString(feeAssetId)).append("\n");
    sb.append("    feeQuantity: ").append(toIndentedString(feeQuantity)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
