/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
import tech.dora.model.Side;
/**
 * Trade
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-14T20:37:48.762145180+01:00[Europe/Paris]")

public class Trade {
  @SerializedName("transaction_id")
  private UUID transactionId = null;

  @SerializedName("asset_0")
  private UUID asset0 = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("fee_asset_id")
  private UUID feeAssetId = null;

  @SerializedName("fee_quantity")
  private String feeQuantity = null;

  @SerializedName("order_book_id")
  private UUID orderBookId = null;

  @SerializedName("order_id")
  private UUID orderId = null;

  @SerializedName("order_seq")
  private Integer orderSeq = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("quantity_0")
  private String quantity0 = null;

  @SerializedName("user_id")
  private UUID userId = null;

  @SerializedName("side")
  private Side side = null;

  @SerializedName("aggressor_indicator")
  private Boolean aggressorIndicator = null;

  public Trade transactionId(UUID transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @Schema(description = "")
  public UUID getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(UUID transactionId) {
    this.transactionId = transactionId;
  }

  public Trade asset0(UUID asset0) {
    this.asset0 = asset0;
    return this;
  }

   /**
   * Get asset0
   * @return asset0
  **/
  @Schema(description = "")
  public UUID getAsset0() {
    return asset0;
  }

  public void setAsset0(UUID asset0) {
    this.asset0 = asset0;
  }

  public Trade createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Trade feeAssetId(UUID feeAssetId) {
    this.feeAssetId = feeAssetId;
    return this;
  }

   /**
   * Get feeAssetId
   * @return feeAssetId
  **/
  @Schema(description = "")
  public UUID getFeeAssetId() {
    return feeAssetId;
  }

  public void setFeeAssetId(UUID feeAssetId) {
    this.feeAssetId = feeAssetId;
  }

  public Trade feeQuantity(String feeQuantity) {
    this.feeQuantity = feeQuantity;
    return this;
  }

   /**
   * Get feeQuantity
   * @return feeQuantity
  **/
  @Schema(description = "")
  public String getFeeQuantity() {
    return feeQuantity;
  }

  public void setFeeQuantity(String feeQuantity) {
    this.feeQuantity = feeQuantity;
  }

  public Trade orderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
    return this;
  }

   /**
   * Get orderBookId
   * @return orderBookId
  **/
  @Schema(description = "")
  public UUID getOrderBookId() {
    return orderBookId;
  }

  public void setOrderBookId(UUID orderBookId) {
    this.orderBookId = orderBookId;
  }

  public Trade orderId(UUID orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @Schema(description = "")
  public UUID getOrderId() {
    return orderId;
  }

  public void setOrderId(UUID orderId) {
    this.orderId = orderId;
  }

  public Trade orderSeq(Integer orderSeq) {
    this.orderSeq = orderSeq;
    return this;
  }

   /**
   * Get orderSeq
   * @return orderSeq
  **/
  @Schema(description = "")
  public Integer getOrderSeq() {
    return orderSeq;
  }

  public void setOrderSeq(Integer orderSeq) {
    this.orderSeq = orderSeq;
  }

  public Trade price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public Trade quantity0(String quantity0) {
    this.quantity0 = quantity0;
    return this;
  }

   /**
   * Get quantity0
   * @return quantity0
  **/
  @Schema(description = "")
  public String getQuantity0() {
    return quantity0;
  }

  public void setQuantity0(String quantity0) {
    this.quantity0 = quantity0;
  }

  public Trade userId(UUID userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  public Trade side(Side side) {
    this.side = side;
    return this;
  }

   /**
   * Get side
   * @return side
  **/
  @Schema(description = "")
  public Side getSide() {
    return side;
  }

  public void setSide(Side side) {
    this.side = side;
  }

  public Trade aggressorIndicator(Boolean aggressorIndicator) {
    this.aggressorIndicator = aggressorIndicator;
    return this;
  }

   /**
   * If true, then this order is the aggressor (taker); otherwise it is the maker.
   * @return aggressorIndicator
  **/
  @Schema(description = "If true, then this order is the aggressor (taker); otherwise it is the maker.")
  public Boolean isAggressorIndicator() {
    return aggressorIndicator;
  }

  public void setAggressorIndicator(Boolean aggressorIndicator) {
    this.aggressorIndicator = aggressorIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trade trade = (Trade) o;
    return Objects.equals(this.transactionId, trade.transactionId) &&
        Objects.equals(this.asset0, trade.asset0) &&
        Objects.equals(this.createdAt, trade.createdAt) &&
        Objects.equals(this.feeAssetId, trade.feeAssetId) &&
        Objects.equals(this.feeQuantity, trade.feeQuantity) &&
        Objects.equals(this.orderBookId, trade.orderBookId) &&
        Objects.equals(this.orderId, trade.orderId) &&
        Objects.equals(this.orderSeq, trade.orderSeq) &&
        Objects.equals(this.price, trade.price) &&
        Objects.equals(this.quantity0, trade.quantity0) &&
        Objects.equals(this.userId, trade.userId) &&
        Objects.equals(this.side, trade.side) &&
        Objects.equals(this.aggressorIndicator, trade.aggressorIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, asset0, createdAt, feeAssetId, feeQuantity, orderBookId, orderId, orderSeq, price, quantity0, userId, side, aggressorIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trade {\n");
    
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    asset0: ").append(toIndentedString(asset0)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    feeAssetId: ").append(toIndentedString(feeAssetId)).append("\n");
    sb.append("    feeQuantity: ").append(toIndentedString(feeQuantity)).append("\n");
    sb.append("    orderBookId: ").append(toIndentedString(orderBookId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderSeq: ").append(toIndentedString(orderSeq)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantity0: ").append(toIndentedString(quantity0)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    side: ").append(toIndentedString(side)).append("\n");
    sb.append("    aggressorIndicator: ").append(toIndentedString(aggressorIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
