/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tech.dora.JSON;

/**
 * TradingChallengeQR
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T04:39:55.054936532+02:00[Europe/Paris]", comments = "Generator version: 7.23.0")
public class TradingChallengeQR {
  public static final String SERIALIZED_NAME_MIN_REWARD_AMOUNT = "min_reward_amount";
  @SerializedName(SERIALIZED_NAME_MIN_REWARD_AMOUNT)
  @javax.annotation.Nonnull
  private String minRewardAmount;

  public static final String SERIALIZED_NAME_MAX_REWARD_AMOUNT = "max_reward_amount";
  @SerializedName(SERIALIZED_NAME_MAX_REWARD_AMOUNT)
  @javax.annotation.Nonnull
  private String maxRewardAmount;

  public static final String SERIALIZED_NAME_REWARD_CLAIM_GRACE_DAYS = "reward_claim_grace_days";
  @SerializedName(SERIALIZED_NAME_REWARD_CLAIM_GRACE_DAYS)
  @javax.annotation.Nonnull
  private Integer rewardClaimGraceDays;

  public static final String SERIALIZED_NAME_CLAIMED_LINKS_COUNT = "claimed_links_count";
  @SerializedName(SERIALIZED_NAME_CLAIMED_LINKS_COUNT)
  @javax.annotation.Nonnull
  private Integer claimedLinksCount;

  public static final String SERIALIZED_NAME_ISSUED_LINKS_COUNT = "issued_links_count";
  @SerializedName(SERIALIZED_NAME_ISSUED_LINKS_COUNT)
  @javax.annotation.Nonnull
  private Integer issuedLinksCount;

  public TradingChallengeQR() {
  }

  public TradingChallengeQR minRewardAmount(@javax.annotation.Nonnull String minRewardAmount) {
    this.minRewardAmount = minRewardAmount;
    return this;
  }

  /**
   * Get minRewardAmount
   * @return minRewardAmount
   */
  @javax.annotation.Nonnull
  public String getMinRewardAmount() {
    return minRewardAmount;
  }

  public void setMinRewardAmount(@javax.annotation.Nonnull String minRewardAmount) {
    this.minRewardAmount = minRewardAmount;
  }


  public TradingChallengeQR maxRewardAmount(@javax.annotation.Nonnull String maxRewardAmount) {
    this.maxRewardAmount = maxRewardAmount;
    return this;
  }

  /**
   * Get maxRewardAmount
   * @return maxRewardAmount
   */
  @javax.annotation.Nonnull
  public String getMaxRewardAmount() {
    return maxRewardAmount;
  }

  public void setMaxRewardAmount(@javax.annotation.Nonnull String maxRewardAmount) {
    this.maxRewardAmount = maxRewardAmount;
  }


  public TradingChallengeQR rewardClaimGraceDays(@javax.annotation.Nonnull Integer rewardClaimGraceDays) {
    this.rewardClaimGraceDays = rewardClaimGraceDays;
    return this;
  }

  /**
   * Get rewardClaimGraceDays
   * @return rewardClaimGraceDays
   */
  @javax.annotation.Nonnull
  public Integer getRewardClaimGraceDays() {
    return rewardClaimGraceDays;
  }

  public void setRewardClaimGraceDays(@javax.annotation.Nonnull Integer rewardClaimGraceDays) {
    this.rewardClaimGraceDays = rewardClaimGraceDays;
  }


  public TradingChallengeQR claimedLinksCount(@javax.annotation.Nonnull Integer claimedLinksCount) {
    this.claimedLinksCount = claimedLinksCount;
    return this;
  }

  /**
   * Get claimedLinksCount
   * @return claimedLinksCount
   */
  @javax.annotation.Nonnull
  public Integer getClaimedLinksCount() {
    return claimedLinksCount;
  }

  public void setClaimedLinksCount(@javax.annotation.Nonnull Integer claimedLinksCount) {
    this.claimedLinksCount = claimedLinksCount;
  }


  public TradingChallengeQR issuedLinksCount(@javax.annotation.Nonnull Integer issuedLinksCount) {
    this.issuedLinksCount = issuedLinksCount;
    return this;
  }

  /**
   * Get issuedLinksCount
   * @return issuedLinksCount
   */
  @javax.annotation.Nonnull
  public Integer getIssuedLinksCount() {
    return issuedLinksCount;
  }

  public void setIssuedLinksCount(@javax.annotation.Nonnull Integer issuedLinksCount) {
    this.issuedLinksCount = issuedLinksCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradingChallengeQR tradingChallengeQR = (TradingChallengeQR) o;
    return Objects.equals(this.minRewardAmount, tradingChallengeQR.minRewardAmount) &&
        Objects.equals(this.maxRewardAmount, tradingChallengeQR.maxRewardAmount) &&
        Objects.equals(this.rewardClaimGraceDays, tradingChallengeQR.rewardClaimGraceDays) &&
        Objects.equals(this.claimedLinksCount, tradingChallengeQR.claimedLinksCount) &&
        Objects.equals(this.issuedLinksCount, tradingChallengeQR.issuedLinksCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minRewardAmount, maxRewardAmount, rewardClaimGraceDays, claimedLinksCount, issuedLinksCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradingChallengeQR {\n");
    sb.append("    minRewardAmount: ").append(toIndentedString(minRewardAmount)).append("\n");
    sb.append("    maxRewardAmount: ").append(toIndentedString(maxRewardAmount)).append("\n");
    sb.append("    rewardClaimGraceDays: ").append(toIndentedString(rewardClaimGraceDays)).append("\n");
    sb.append("    claimedLinksCount: ").append(toIndentedString(claimedLinksCount)).append("\n");
    sb.append("    issuedLinksCount: ").append(toIndentedString(issuedLinksCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("min_reward_amount", "max_reward_amount", "reward_claim_grace_days", "claimed_links_count", "issued_links_count"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("min_reward_amount", "max_reward_amount", "reward_claim_grace_days", "claimed_links_count", "issued_links_count"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TradingChallengeQR
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TradingChallengeQR.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TradingChallengeQR is not found in the empty JSON string", TradingChallengeQR.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TradingChallengeQR.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TradingChallengeQR` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TradingChallengeQR.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("min_reward_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `min_reward_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("min_reward_amount").toString()));
      }
      if (!jsonObj.get("max_reward_amount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `max_reward_amount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("max_reward_amount").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TradingChallengeQR.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TradingChallengeQR' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TradingChallengeQR> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TradingChallengeQR.class));

       return (TypeAdapter<T>) new TypeAdapter<TradingChallengeQR>() {
           @Override
           public void write(JsonWriter out, TradingChallengeQR value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TradingChallengeQR read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TradingChallengeQR given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TradingChallengeQR
   * @throws IOException if the JSON string is invalid with respect to TradingChallengeQR
   */
  public static TradingChallengeQR fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TradingChallengeQR.class);
  }

  /**
   * Convert an instance of TradingChallengeQR to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

