/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TransformedAssets
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-03-20T17:06:55.829868863+01:00[Europe/Paris]")

public class TransformedAssets {
  @SerializedName("gained")
  private Object gained = null;

  @SerializedName("lost")
  private Object lost = null;

  public TransformedAssets gained(Object gained) {
    this.gained = gained;
    return this;
  }

   /**
   * Assets that have been gained by stablecoin equivalence transformations. They cannot be withdrawn from the platform until converted back to the original asset.
   * @return gained
  **/
  @Schema(description = "Assets that have been gained by stablecoin equivalence transformations. They cannot be withdrawn from the platform until converted back to the original asset.")
  public Object getGained() {
    return gained;
  }

  public void setGained(Object gained) {
    this.gained = gained;
  }

  public TransformedAssets lost(Object lost) {
    this.lost = lost;
    return this;
  }

   /**
   * Assets that have been lost by stablecoin equivalence transformations. They can be recovered by converting back any assets gained by stablecoin equivalence transformations.
   * @return lost
  **/
  @Schema(description = "Assets that have been lost by stablecoin equivalence transformations. They can be recovered by converting back any assets gained by stablecoin equivalence transformations.")
  public Object getLost() {
    return lost;
  }

  public void setLost(Object lost) {
    this.lost = lost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransformedAssets transformedAssets = (TransformedAssets) o;
    return Objects.equals(this.gained, transformedAssets.gained) &&
        Objects.equals(this.lost, transformedAssets.lost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gained, lost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransformedAssets {\n");
    
    sb.append("    gained: ").append(toIndentedString(gained)).append("\n");
    sb.append("    lost: ").append(toIndentedString(lost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
