/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tech.dora.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
/**
 * TransferBalancesRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-14T17:31:47.069436198+01:00[Europe/Paris]")

public class TransferBalancesRequest {
  @SerializedName("from_position_id")
  private UUID fromPositionId = null;

  @SerializedName("to_position_id")
  private UUID toPositionId = null;

  @SerializedName("asset_id")
  private UUID assetId = null;

  @SerializedName("quantity")
  private String quantity = null;

  public TransferBalancesRequest fromPositionId(UUID fromPositionId) {
    this.fromPositionId = fromPositionId;
    return this;
  }

   /**
   * Get fromPositionId
   * @return fromPositionId
  **/
  @Schema(required = true, description = "")
  public UUID getFromPositionId() {
    return fromPositionId;
  }

  public void setFromPositionId(UUID fromPositionId) {
    this.fromPositionId = fromPositionId;
  }

  public TransferBalancesRequest toPositionId(UUID toPositionId) {
    this.toPositionId = toPositionId;
    return this;
  }

   /**
   * Get toPositionId
   * @return toPositionId
  **/
  @Schema(required = true, description = "")
  public UUID getToPositionId() {
    return toPositionId;
  }

  public void setToPositionId(UUID toPositionId) {
    this.toPositionId = toPositionId;
  }

  public TransferBalancesRequest assetId(UUID assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Get assetId
   * @return assetId
  **/
  @Schema(required = true, description = "")
  public UUID getAssetId() {
    return assetId;
  }

  public void setAssetId(UUID assetId) {
    this.assetId = assetId;
  }

  public TransferBalancesRequest quantity(String quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(required = true, description = "")
  public String getQuantity() {
    return quantity;
  }

  public void setQuantity(String quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferBalancesRequest transferBalancesRequest = (TransferBalancesRequest) o;
    return Objects.equals(this.fromPositionId, transferBalancesRequest.fromPositionId) &&
        Objects.equals(this.toPositionId, transferBalancesRequest.toPositionId) &&
        Objects.equals(this.assetId, transferBalancesRequest.assetId) &&
        Objects.equals(this.quantity, transferBalancesRequest.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromPositionId, toPositionId, assetId, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferBalancesRequest {\n");
    
    sb.append("    fromPositionId: ").append(toIndentedString(fromPositionId)).append("\n");
    sb.append("    toPositionId: ").append(toIndentedString(toPositionId)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
