/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import tech.dora.model.UpdateFieldBoolean;
import tech.dora.model.UpdateFieldString;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import tech.dora.JSON;

/**
 * Request body for PUT /user/{id}/config: update a user changeable details only. Other properties can only be changed by an admin following a manual request by the user.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-02T17:13:50.947925667+02:00[Europe/Paris]", comments = "Generator version: 7.17.0")
public class UpdateUserConfigRequest {
  public static final String SERIALIZED_NAME_PHOTO_URL = "photo_url";
  @SerializedName(SERIALIZED_NAME_PHOTO_URL)
  @javax.annotation.Nullable
  private UpdateFieldString photoUrl;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nonnull
  private UpdateFieldString timezone;

  public static final String SERIALIZED_NAME_SHOW_TUTORIAL_CARDS = "show_tutorial_cards";
  @SerializedName(SERIALIZED_NAME_SHOW_TUTORIAL_CARDS)
  @javax.annotation.Nullable
  private UpdateFieldBoolean showTutorialCards;

  public static final String SERIALIZED_NAME_NOTIFICATIONS_ENABLED = "notifications_enabled";
  @SerializedName(SERIALIZED_NAME_NOTIFICATIONS_ENABLED)
  @javax.annotation.Nullable
  private UpdateFieldBoolean notificationsEnabled;

  public static final String SERIALIZED_NAME_ALLOW_EMAIL_NOTIFICATIONS = "allow_email_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_EMAIL_NOTIFICATIONS)
  @javax.annotation.Nullable
  private UpdateFieldBoolean allowEmailNotifications;

  public static final String SERIALIZED_NAME_ALLOW_LIQUIDATIONS_NOTIFICATIONS = "allow_liquidations_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_LIQUIDATIONS_NOTIFICATIONS)
  @javax.annotation.Nullable
  private UpdateFieldBoolean allowLiquidationsNotifications;

  public static final String SERIALIZED_NAME_ALLOW_DEPOSIT_WITHDRAWAL_NOTIFICATIONS = "allow_deposit_withdrawal_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_DEPOSIT_WITHDRAWAL_NOTIFICATIONS)
  @javax.annotation.Nullable
  private UpdateFieldBoolean allowDepositWithdrawalNotifications;

  public static final String SERIALIZED_NAME_ALLOW_ORDERS_NOTIFICATIONS = "allow_orders_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_ORDERS_NOTIFICATIONS)
  @javax.annotation.Nullable
  private UpdateFieldBoolean allowOrdersNotifications;

  public UpdateUserConfigRequest() {
  }

  public UpdateUserConfigRequest photoUrl(@javax.annotation.Nullable UpdateFieldString photoUrl) {
    this.photoUrl = photoUrl;
    return this;
  }

  /**
   * Optional: URL of the user&#39;s profile photo, optional.
   * @return photoUrl
   */
  @javax.annotation.Nullable
  public UpdateFieldString getPhotoUrl() {
    return photoUrl;
  }

  public void setPhotoUrl(@javax.annotation.Nullable UpdateFieldString photoUrl) {
    this.photoUrl = photoUrl;
  }


  public UpdateUserConfigRequest timezone(@javax.annotation.Nonnull UpdateFieldString timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * User&#39;s timezone, e.g., &#39;America/New_York&#39;, or an offset.
   * @return timezone
   */
  @javax.annotation.Nonnull
  public UpdateFieldString getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nonnull UpdateFieldString timezone) {
    this.timezone = timezone;
  }


  public UpdateUserConfigRequest showTutorialCards(@javax.annotation.Nullable UpdateFieldBoolean showTutorialCards) {
    this.showTutorialCards = showTutorialCards;
    return this;
  }

  /**
   * Optional: Whether to show the tutorial.
   * @return showTutorialCards
   */
  @javax.annotation.Nullable
  public UpdateFieldBoolean getShowTutorialCards() {
    return showTutorialCards;
  }

  public void setShowTutorialCards(@javax.annotation.Nullable UpdateFieldBoolean showTutorialCards) {
    this.showTutorialCards = showTutorialCards;
  }


  public UpdateUserConfigRequest notificationsEnabled(@javax.annotation.Nullable UpdateFieldBoolean notificationsEnabled) {
    this.notificationsEnabled = notificationsEnabled;
    return this;
  }

  /**
   * Optional: Whether to show the notifications.
   * @return notificationsEnabled
   */
  @javax.annotation.Nullable
  public UpdateFieldBoolean getNotificationsEnabled() {
    return notificationsEnabled;
  }

  public void setNotificationsEnabled(@javax.annotation.Nullable UpdateFieldBoolean notificationsEnabled) {
    this.notificationsEnabled = notificationsEnabled;
  }


  public UpdateUserConfigRequest allowEmailNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowEmailNotifications) {
    this.allowEmailNotifications = allowEmailNotifications;
    return this;
  }

  /**
   * Optional: Whether to allow email notifications.
   * @return allowEmailNotifications
   */
  @javax.annotation.Nullable
  public UpdateFieldBoolean getAllowEmailNotifications() {
    return allowEmailNotifications;
  }

  public void setAllowEmailNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowEmailNotifications) {
    this.allowEmailNotifications = allowEmailNotifications;
  }


  public UpdateUserConfigRequest allowLiquidationsNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowLiquidationsNotifications) {
    this.allowLiquidationsNotifications = allowLiquidationsNotifications;
    return this;
  }

  /**
   * Optional: Whether to allow liquidations notifications.
   * @return allowLiquidationsNotifications
   */
  @javax.annotation.Nullable
  public UpdateFieldBoolean getAllowLiquidationsNotifications() {
    return allowLiquidationsNotifications;
  }

  public void setAllowLiquidationsNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowLiquidationsNotifications) {
    this.allowLiquidationsNotifications = allowLiquidationsNotifications;
  }


  public UpdateUserConfigRequest allowDepositWithdrawalNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowDepositWithdrawalNotifications) {
    this.allowDepositWithdrawalNotifications = allowDepositWithdrawalNotifications;
    return this;
  }

  /**
   * Optional: Whether to allow deposit/withdrawal notifications.
   * @return allowDepositWithdrawalNotifications
   */
  @javax.annotation.Nullable
  public UpdateFieldBoolean getAllowDepositWithdrawalNotifications() {
    return allowDepositWithdrawalNotifications;
  }

  public void setAllowDepositWithdrawalNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowDepositWithdrawalNotifications) {
    this.allowDepositWithdrawalNotifications = allowDepositWithdrawalNotifications;
  }


  public UpdateUserConfigRequest allowOrdersNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowOrdersNotifications) {
    this.allowOrdersNotifications = allowOrdersNotifications;
    return this;
  }

  /**
   * Optional: Whether to allow orders notifications.
   * @return allowOrdersNotifications
   */
  @javax.annotation.Nullable
  public UpdateFieldBoolean getAllowOrdersNotifications() {
    return allowOrdersNotifications;
  }

  public void setAllowOrdersNotifications(@javax.annotation.Nullable UpdateFieldBoolean allowOrdersNotifications) {
    this.allowOrdersNotifications = allowOrdersNotifications;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserConfigRequest updateUserConfigRequest = (UpdateUserConfigRequest) o;
    return Objects.equals(this.photoUrl, updateUserConfigRequest.photoUrl) &&
        Objects.equals(this.timezone, updateUserConfigRequest.timezone) &&
        Objects.equals(this.showTutorialCards, updateUserConfigRequest.showTutorialCards) &&
        Objects.equals(this.notificationsEnabled, updateUserConfigRequest.notificationsEnabled) &&
        Objects.equals(this.allowEmailNotifications, updateUserConfigRequest.allowEmailNotifications) &&
        Objects.equals(this.allowLiquidationsNotifications, updateUserConfigRequest.allowLiquidationsNotifications) &&
        Objects.equals(this.allowDepositWithdrawalNotifications, updateUserConfigRequest.allowDepositWithdrawalNotifications) &&
        Objects.equals(this.allowOrdersNotifications, updateUserConfigRequest.allowOrdersNotifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(photoUrl, timezone, showTutorialCards, notificationsEnabled, allowEmailNotifications, allowLiquidationsNotifications, allowDepositWithdrawalNotifications, allowOrdersNotifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserConfigRequest {\n");
    sb.append("    photoUrl: ").append(toIndentedString(photoUrl)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    showTutorialCards: ").append(toIndentedString(showTutorialCards)).append("\n");
    sb.append("    notificationsEnabled: ").append(toIndentedString(notificationsEnabled)).append("\n");
    sb.append("    allowEmailNotifications: ").append(toIndentedString(allowEmailNotifications)).append("\n");
    sb.append("    allowLiquidationsNotifications: ").append(toIndentedString(allowLiquidationsNotifications)).append("\n");
    sb.append("    allowDepositWithdrawalNotifications: ").append(toIndentedString(allowDepositWithdrawalNotifications)).append("\n");
    sb.append("    allowOrdersNotifications: ").append(toIndentedString(allowOrdersNotifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("photo_url", "timezone", "show_tutorial_cards", "notifications_enabled", "allow_email_notifications", "allow_liquidations_notifications", "allow_deposit_withdrawal_notifications", "allow_orders_notifications"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("timezone"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateUserConfigRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateUserConfigRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in UpdateUserConfigRequest is not found in the empty JSON string", UpdateUserConfigRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateUserConfigRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateUserConfigRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateUserConfigRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `photo_url`
      if (jsonObj.get("photo_url") != null && !jsonObj.get("photo_url").isJsonNull()) {
        UpdateFieldString.validateJsonElement(jsonObj.get("photo_url"));
      }
      // validate the required field `timezone`
      UpdateFieldString.validateJsonElement(jsonObj.get("timezone"));
      // validate the optional field `show_tutorial_cards`
      if (jsonObj.get("show_tutorial_cards") != null && !jsonObj.get("show_tutorial_cards").isJsonNull()) {
        UpdateFieldBoolean.validateJsonElement(jsonObj.get("show_tutorial_cards"));
      }
      // validate the optional field `notifications_enabled`
      if (jsonObj.get("notifications_enabled") != null && !jsonObj.get("notifications_enabled").isJsonNull()) {
        UpdateFieldBoolean.validateJsonElement(jsonObj.get("notifications_enabled"));
      }
      // validate the optional field `allow_email_notifications`
      if (jsonObj.get("allow_email_notifications") != null && !jsonObj.get("allow_email_notifications").isJsonNull()) {
        UpdateFieldBoolean.validateJsonElement(jsonObj.get("allow_email_notifications"));
      }
      // validate the optional field `allow_liquidations_notifications`
      if (jsonObj.get("allow_liquidations_notifications") != null && !jsonObj.get("allow_liquidations_notifications").isJsonNull()) {
        UpdateFieldBoolean.validateJsonElement(jsonObj.get("allow_liquidations_notifications"));
      }
      // validate the optional field `allow_deposit_withdrawal_notifications`
      if (jsonObj.get("allow_deposit_withdrawal_notifications") != null && !jsonObj.get("allow_deposit_withdrawal_notifications").isJsonNull()) {
        UpdateFieldBoolean.validateJsonElement(jsonObj.get("allow_deposit_withdrawal_notifications"));
      }
      // validate the optional field `allow_orders_notifications`
      if (jsonObj.get("allow_orders_notifications") != null && !jsonObj.get("allow_orders_notifications").isJsonNull()) {
        UpdateFieldBoolean.validateJsonElement(jsonObj.get("allow_orders_notifications"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateUserConfigRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateUserConfigRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateUserConfigRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateUserConfigRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateUserConfigRequest>() {
           @Override
           public void write(JsonWriter out, UpdateUserConfigRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateUserConfigRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateUserConfigRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateUserConfigRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateUserConfigRequest
   */
  public static UpdateUserConfigRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateUserConfigRequest.class);
  }

  /**
   * Convert an instance of UpdateUserConfigRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

