/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import tech.dora.model.UpdateFieldDateTime;
import tech.dora.model.UpdateFieldDecimal;
import tech.dora.model.UpdateFieldInteger;
import tech.dora.model.UpdateFieldString;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import tech.dora.JSON;

/**
 * Request body for PUT /v1/trading_challenges/{trading_challenge_id}: partially update a trading challenge. A field that is omitted, or sent as null, is left unchanged. Each field accepts either the {update, value} object or the bare value on its own. PENDING challenges accept every field; ACTIVE challenges accept only name, max_users, end and the prize quantities; COMPLETED challenges accept none. tenant_id and status are never updatable, and the participant list is managed by add_users and remove_users.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-31T11:19:20.004337973+02:00[Europe/Paris]", comments = "Generator version: 7.23.0")
public class UpdateTradingChallengeRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private UpdateFieldString name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private UpdateFieldString type;

  public static final String SERIALIZED_NAME_MAX_USERS = "max_users";
  @SerializedName(SERIALIZED_NAME_MAX_USERS)
  @javax.annotation.Nullable
  private UpdateFieldInteger maxUsers;

  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  @javax.annotation.Nullable
  private UpdateFieldDateTime start;

  public static final String SERIALIZED_NAME_END = "end";
  @SerializedName(SERIALIZED_NAME_END)
  @javax.annotation.Nullable
  private UpdateFieldDateTime end;

  public static final String SERIALIZED_NAME_INITIAL_USER_BALANCE = "initial_user_balance";
  @SerializedName(SERIALIZED_NAME_INITIAL_USER_BALANCE)
  @javax.annotation.Nullable
  private UpdateFieldDecimal initialUserBalance;

  public static final String SERIALIZED_NAME_GOLD_PRIZE_QUANTITY = "gold_prize_quantity";
  @SerializedName(SERIALIZED_NAME_GOLD_PRIZE_QUANTITY)
  @javax.annotation.Nullable
  private UpdateFieldDecimal goldPrizeQuantity;

  public static final String SERIALIZED_NAME_SILVER_PRIZE_QUANTITY = "silver_prize_quantity";
  @SerializedName(SERIALIZED_NAME_SILVER_PRIZE_QUANTITY)
  @javax.annotation.Nullable
  private UpdateFieldDecimal silverPrizeQuantity;

  public static final String SERIALIZED_NAME_BRONZE_PRIZE_QUANTITY = "bronze_prize_quantity";
  @SerializedName(SERIALIZED_NAME_BRONZE_PRIZE_QUANTITY)
  @javax.annotation.Nullable
  private UpdateFieldDecimal bronzePrizeQuantity;

  public static final String SERIALIZED_NAME_PNL_CONDITION = "pnl_condition";
  @SerializedName(SERIALIZED_NAME_PNL_CONDITION)
  @javax.annotation.Nullable
  private UpdateFieldDecimal pnlCondition;

  public static final String SERIALIZED_NAME_TOTAL_VOLUME_CONDITION = "total_volume_condition";
  @SerializedName(SERIALIZED_NAME_TOTAL_VOLUME_CONDITION)
  @javax.annotation.Nullable
  private UpdateFieldDecimal totalVolumeCondition;

  public static final String SERIALIZED_NAME_AVG_DAILY_VOLUME_CONDITION = "avg_daily_volume_condition";
  @SerializedName(SERIALIZED_NAME_AVG_DAILY_VOLUME_CONDITION)
  @javax.annotation.Nullable
  private UpdateFieldDecimal avgDailyVolumeCondition;

  public static final String SERIALIZED_NAME_MINIMUM_EQUITY_PERCENTAGE_CONDITION = "minimum_equity_percentage_condition";
  @SerializedName(SERIALIZED_NAME_MINIMUM_EQUITY_PERCENTAGE_CONDITION)
  @javax.annotation.Nullable
  private UpdateFieldInteger minimumEquityPercentageCondition;

  public UpdateTradingChallengeRequest() {
  }

  public UpdateTradingChallengeRequest name(@javax.annotation.Nullable UpdateFieldString name) {
    this.name = name;
    return this;
  }

  /**
   * Trading challenge name.
   * @return name
   */
  @javax.annotation.Nullable
  public UpdateFieldString getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable UpdateFieldString name) {
    this.name = name;
  }


  public UpdateTradingChallengeRequest type(@javax.annotation.Nullable UpdateFieldString type) {
    this.type = type;
    return this;
  }

  /**
   * CASH or TOURNAMENT. Only updatable while the challenge is PENDING.
   * @return type
   */
  @javax.annotation.Nullable
  public UpdateFieldString getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable UpdateFieldString type) {
    this.type = type;
  }


  public UpdateTradingChallengeRequest maxUsers(@javax.annotation.Nullable UpdateFieldInteger maxUsers) {
    this.maxUsers = maxUsers;
    return this;
  }

  /**
   * Must be &gt; 0 and cannot be lowered below the number of users already registered.
   * @return maxUsers
   */
  @javax.annotation.Nullable
  public UpdateFieldInteger getMaxUsers() {
    return maxUsers;
  }

  public void setMaxUsers(@javax.annotation.Nullable UpdateFieldInteger maxUsers) {
    this.maxUsers = maxUsers;
  }


  public UpdateTradingChallengeRequest start(@javax.annotation.Nullable UpdateFieldDateTime start) {
    this.start = start;
    return this;
  }

  /**
   * Only updatable while the challenge is PENDING.
   * @return start
   */
  @javax.annotation.Nullable
  public UpdateFieldDateTime getStart() {
    return start;
  }

  public void setStart(@javax.annotation.Nullable UpdateFieldDateTime start) {
    this.start = start;
  }


  public UpdateTradingChallengeRequest end(@javax.annotation.Nullable UpdateFieldDateTime end) {
    this.end = end;
    return this;
  }

  /**
   * Must be after start and in the future.
   * @return end
   */
  @javax.annotation.Nullable
  public UpdateFieldDateTime getEnd() {
    return end;
  }

  public void setEnd(@javax.annotation.Nullable UpdateFieldDateTime end) {
    this.end = end;
  }


  public UpdateTradingChallengeRequest initialUserBalance(@javax.annotation.Nullable UpdateFieldDecimal initialUserBalance) {
    this.initialUserBalance = initialUserBalance;
    return this;
  }

  /**
   * Must be &gt; 0. Only updatable while the challenge is PENDING.
   * @return initialUserBalance
   */
  @javax.annotation.Nullable
  public UpdateFieldDecimal getInitialUserBalance() {
    return initialUserBalance;
  }

  public void setInitialUserBalance(@javax.annotation.Nullable UpdateFieldDecimal initialUserBalance) {
    this.initialUserBalance = initialUserBalance;
  }


  public UpdateTradingChallengeRequest goldPrizeQuantity(@javax.annotation.Nullable UpdateFieldDecimal goldPrizeQuantity) {
    this.goldPrizeQuantity = goldPrizeQuantity;
    return this;
  }

  /**
   * Must be &gt; 0 for a TOURNAMENT challenge.
   * @return goldPrizeQuantity
   */
  @javax.annotation.Nullable
  public UpdateFieldDecimal getGoldPrizeQuantity() {
    return goldPrizeQuantity;
  }

  public void setGoldPrizeQuantity(@javax.annotation.Nullable UpdateFieldDecimal goldPrizeQuantity) {
    this.goldPrizeQuantity = goldPrizeQuantity;
  }


  public UpdateTradingChallengeRequest silverPrizeQuantity(@javax.annotation.Nullable UpdateFieldDecimal silverPrizeQuantity) {
    this.silverPrizeQuantity = silverPrizeQuantity;
    return this;
  }

  /**
   * Must be &gt;&#x3D; 0.
   * @return silverPrizeQuantity
   */
  @javax.annotation.Nullable
  public UpdateFieldDecimal getSilverPrizeQuantity() {
    return silverPrizeQuantity;
  }

  public void setSilverPrizeQuantity(@javax.annotation.Nullable UpdateFieldDecimal silverPrizeQuantity) {
    this.silverPrizeQuantity = silverPrizeQuantity;
  }


  public UpdateTradingChallengeRequest bronzePrizeQuantity(@javax.annotation.Nullable UpdateFieldDecimal bronzePrizeQuantity) {
    this.bronzePrizeQuantity = bronzePrizeQuantity;
    return this;
  }

  /**
   * Must be &gt;&#x3D; 0.
   * @return bronzePrizeQuantity
   */
  @javax.annotation.Nullable
  public UpdateFieldDecimal getBronzePrizeQuantity() {
    return bronzePrizeQuantity;
  }

  public void setBronzePrizeQuantity(@javax.annotation.Nullable UpdateFieldDecimal bronzePrizeQuantity) {
    this.bronzePrizeQuantity = bronzePrizeQuantity;
  }


  public UpdateTradingChallengeRequest pnlCondition(@javax.annotation.Nullable UpdateFieldDecimal pnlCondition) {
    this.pnlCondition = pnlCondition;
    return this;
  }

  /**
   * Must be &gt;&#x3D; 0. Only updatable while the challenge is PENDING.
   * @return pnlCondition
   */
  @javax.annotation.Nullable
  public UpdateFieldDecimal getPnlCondition() {
    return pnlCondition;
  }

  public void setPnlCondition(@javax.annotation.Nullable UpdateFieldDecimal pnlCondition) {
    this.pnlCondition = pnlCondition;
  }


  public UpdateTradingChallengeRequest totalVolumeCondition(@javax.annotation.Nullable UpdateFieldDecimal totalVolumeCondition) {
    this.totalVolumeCondition = totalVolumeCondition;
    return this;
  }

  /**
   * Must be &gt;&#x3D; 0. Only updatable while the challenge is PENDING.
   * @return totalVolumeCondition
   */
  @javax.annotation.Nullable
  public UpdateFieldDecimal getTotalVolumeCondition() {
    return totalVolumeCondition;
  }

  public void setTotalVolumeCondition(@javax.annotation.Nullable UpdateFieldDecimal totalVolumeCondition) {
    this.totalVolumeCondition = totalVolumeCondition;
  }


  public UpdateTradingChallengeRequest avgDailyVolumeCondition(@javax.annotation.Nullable UpdateFieldDecimal avgDailyVolumeCondition) {
    this.avgDailyVolumeCondition = avgDailyVolumeCondition;
    return this;
  }

  /**
   * Must be &gt;&#x3D; 0. Only updatable while the challenge is PENDING.
   * @return avgDailyVolumeCondition
   */
  @javax.annotation.Nullable
  public UpdateFieldDecimal getAvgDailyVolumeCondition() {
    return avgDailyVolumeCondition;
  }

  public void setAvgDailyVolumeCondition(@javax.annotation.Nullable UpdateFieldDecimal avgDailyVolumeCondition) {
    this.avgDailyVolumeCondition = avgDailyVolumeCondition;
  }


  public UpdateTradingChallengeRequest minimumEquityPercentageCondition(@javax.annotation.Nullable UpdateFieldInteger minimumEquityPercentageCondition) {
    this.minimumEquityPercentageCondition = minimumEquityPercentageCondition;
    return this;
  }

  /**
   * In the range [0,100). Only updatable while the challenge is PENDING.
   * @return minimumEquityPercentageCondition
   */
  @javax.annotation.Nullable
  public UpdateFieldInteger getMinimumEquityPercentageCondition() {
    return minimumEquityPercentageCondition;
  }

  public void setMinimumEquityPercentageCondition(@javax.annotation.Nullable UpdateFieldInteger minimumEquityPercentageCondition) {
    this.minimumEquityPercentageCondition = minimumEquityPercentageCondition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateTradingChallengeRequest updateTradingChallengeRequest = (UpdateTradingChallengeRequest) o;
    return Objects.equals(this.name, updateTradingChallengeRequest.name) &&
        Objects.equals(this.type, updateTradingChallengeRequest.type) &&
        Objects.equals(this.maxUsers, updateTradingChallengeRequest.maxUsers) &&
        Objects.equals(this.start, updateTradingChallengeRequest.start) &&
        Objects.equals(this.end, updateTradingChallengeRequest.end) &&
        Objects.equals(this.initialUserBalance, updateTradingChallengeRequest.initialUserBalance) &&
        Objects.equals(this.goldPrizeQuantity, updateTradingChallengeRequest.goldPrizeQuantity) &&
        Objects.equals(this.silverPrizeQuantity, updateTradingChallengeRequest.silverPrizeQuantity) &&
        Objects.equals(this.bronzePrizeQuantity, updateTradingChallengeRequest.bronzePrizeQuantity) &&
        Objects.equals(this.pnlCondition, updateTradingChallengeRequest.pnlCondition) &&
        Objects.equals(this.totalVolumeCondition, updateTradingChallengeRequest.totalVolumeCondition) &&
        Objects.equals(this.avgDailyVolumeCondition, updateTradingChallengeRequest.avgDailyVolumeCondition) &&
        Objects.equals(this.minimumEquityPercentageCondition, updateTradingChallengeRequest.minimumEquityPercentageCondition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, maxUsers, start, end, initialUserBalance, goldPrizeQuantity, silverPrizeQuantity, bronzePrizeQuantity, pnlCondition, totalVolumeCondition, avgDailyVolumeCondition, minimumEquityPercentageCondition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTradingChallengeRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    maxUsers: ").append(toIndentedString(maxUsers)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    initialUserBalance: ").append(toIndentedString(initialUserBalance)).append("\n");
    sb.append("    goldPrizeQuantity: ").append(toIndentedString(goldPrizeQuantity)).append("\n");
    sb.append("    silverPrizeQuantity: ").append(toIndentedString(silverPrizeQuantity)).append("\n");
    sb.append("    bronzePrizeQuantity: ").append(toIndentedString(bronzePrizeQuantity)).append("\n");
    sb.append("    pnlCondition: ").append(toIndentedString(pnlCondition)).append("\n");
    sb.append("    totalVolumeCondition: ").append(toIndentedString(totalVolumeCondition)).append("\n");
    sb.append("    avgDailyVolumeCondition: ").append(toIndentedString(avgDailyVolumeCondition)).append("\n");
    sb.append("    minimumEquityPercentageCondition: ").append(toIndentedString(minimumEquityPercentageCondition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "type", "max_users", "start", "end", "initial_user_balance", "gold_prize_quantity", "silver_prize_quantity", "bronze_prize_quantity", "pnl_condition", "total_volume_condition", "avg_daily_volume_condition", "minimum_equity_percentage_condition"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateTradingChallengeRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateTradingChallengeRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateTradingChallengeRequest is not found in the empty JSON string", UpdateTradingChallengeRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateTradingChallengeRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateTradingChallengeRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `name`
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) {
        UpdateFieldString.validateJsonElement(jsonObj.get("name"));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        UpdateFieldString.validateJsonElement(jsonObj.get("type"));
      }
      // validate the optional field `max_users`
      if (jsonObj.get("max_users") != null && !jsonObj.get("max_users").isJsonNull()) {
        UpdateFieldInteger.validateJsonElement(jsonObj.get("max_users"));
      }
      // validate the optional field `start`
      if (jsonObj.get("start") != null && !jsonObj.get("start").isJsonNull()) {
        UpdateFieldDateTime.validateJsonElement(jsonObj.get("start"));
      }
      // validate the optional field `end`
      if (jsonObj.get("end") != null && !jsonObj.get("end").isJsonNull()) {
        UpdateFieldDateTime.validateJsonElement(jsonObj.get("end"));
      }
      // validate the optional field `initial_user_balance`
      if (jsonObj.get("initial_user_balance") != null && !jsonObj.get("initial_user_balance").isJsonNull()) {
        UpdateFieldDecimal.validateJsonElement(jsonObj.get("initial_user_balance"));
      }
      // validate the optional field `gold_prize_quantity`
      if (jsonObj.get("gold_prize_quantity") != null && !jsonObj.get("gold_prize_quantity").isJsonNull()) {
        UpdateFieldDecimal.validateJsonElement(jsonObj.get("gold_prize_quantity"));
      }
      // validate the optional field `silver_prize_quantity`
      if (jsonObj.get("silver_prize_quantity") != null && !jsonObj.get("silver_prize_quantity").isJsonNull()) {
        UpdateFieldDecimal.validateJsonElement(jsonObj.get("silver_prize_quantity"));
      }
      // validate the optional field `bronze_prize_quantity`
      if (jsonObj.get("bronze_prize_quantity") != null && !jsonObj.get("bronze_prize_quantity").isJsonNull()) {
        UpdateFieldDecimal.validateJsonElement(jsonObj.get("bronze_prize_quantity"));
      }
      // validate the optional field `pnl_condition`
      if (jsonObj.get("pnl_condition") != null && !jsonObj.get("pnl_condition").isJsonNull()) {
        UpdateFieldDecimal.validateJsonElement(jsonObj.get("pnl_condition"));
      }
      // validate the optional field `total_volume_condition`
      if (jsonObj.get("total_volume_condition") != null && !jsonObj.get("total_volume_condition").isJsonNull()) {
        UpdateFieldDecimal.validateJsonElement(jsonObj.get("total_volume_condition"));
      }
      // validate the optional field `avg_daily_volume_condition`
      if (jsonObj.get("avg_daily_volume_condition") != null && !jsonObj.get("avg_daily_volume_condition").isJsonNull()) {
        UpdateFieldDecimal.validateJsonElement(jsonObj.get("avg_daily_volume_condition"));
      }
      // validate the optional field `minimum_equity_percentage_condition`
      if (jsonObj.get("minimum_equity_percentage_condition") != null && !jsonObj.get("minimum_equity_percentage_condition").isJsonNull()) {
        UpdateFieldInteger.validateJsonElement(jsonObj.get("minimum_equity_percentage_condition"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateTradingChallengeRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateTradingChallengeRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateTradingChallengeRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateTradingChallengeRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateTradingChallengeRequest>() {
           @Override
           public void write(JsonWriter out, UpdateTradingChallengeRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateTradingChallengeRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateTradingChallengeRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateTradingChallengeRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateTradingChallengeRequest
   */
  public static UpdateTradingChallengeRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateTradingChallengeRequest.class);
  }

  /**
   * Convert an instance of UpdateTradingChallengeRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

