/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import tech.dora.JSON;

/**
 * UserConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-02T17:13:50.947925667+02:00[Europe/Paris]", comments = "Generator version: 7.17.0")
public class UserConfig {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_PHOTO_URL = "photo_url";
  @SerializedName(SERIALIZED_NAME_PHOTO_URL)
  @javax.annotation.Nullable
  private String photoUrl;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_SHOW_TUTORIAL_CARDS = "show_tutorial_cards";
  @SerializedName(SERIALIZED_NAME_SHOW_TUTORIAL_CARDS)
  @javax.annotation.Nonnull
  private Boolean showTutorialCards;

  public static final String SERIALIZED_NAME_NOTIFICATIONS_ENABLED = "notifications_enabled";
  @SerializedName(SERIALIZED_NAME_NOTIFICATIONS_ENABLED)
  @javax.annotation.Nonnull
  private Boolean notificationsEnabled;

  public static final String SERIALIZED_NAME_ALLOW_EMAIL_NOTIFICATIONS = "allow_email_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_EMAIL_NOTIFICATIONS)
  @javax.annotation.Nonnull
  private Boolean allowEmailNotifications;

  public static final String SERIALIZED_NAME_ALLOW_LIQUIDATIONS_NOTIFICATIONS = "allow_liquidations_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_LIQUIDATIONS_NOTIFICATIONS)
  @javax.annotation.Nonnull
  private Boolean allowLiquidationsNotifications;

  public static final String SERIALIZED_NAME_ALLOW_DEPOSIT_WITHDRAWAL_NOTIFICATIONS = "allow_deposit_withdrawal_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_DEPOSIT_WITHDRAWAL_NOTIFICATIONS)
  @javax.annotation.Nonnull
  private Boolean allowDepositWithdrawalNotifications;

  public static final String SERIALIZED_NAME_ALLOW_ORDERS_NOTIFICATIONS = "allow_orders_notifications";
  @SerializedName(SERIALIZED_NAME_ALLOW_ORDERS_NOTIFICATIONS)
  @javax.annotation.Nonnull
  private Boolean allowOrdersNotifications;

  public UserConfig() {
  }

  public UserConfig id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public UserConfig photoUrl(@javax.annotation.Nullable String photoUrl) {
    this.photoUrl = photoUrl;
    return this;
  }

  /**
   * Get photoUrl
   * @return photoUrl
   */
  @javax.annotation.Nullable
  public String getPhotoUrl() {
    return photoUrl;
  }

  public void setPhotoUrl(@javax.annotation.Nullable String photoUrl) {
    this.photoUrl = photoUrl;
  }


  public UserConfig timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * User&#39;s timezone, e.g., &#39;America/New_York&#39;, or an offset.
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  public UserConfig createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public UserConfig updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public UserConfig showTutorialCards(@javax.annotation.Nonnull Boolean showTutorialCards) {
    this.showTutorialCards = showTutorialCards;
    return this;
  }

  /**
   * Get showTutorialCards
   * @return showTutorialCards
   */
  @javax.annotation.Nonnull
  public Boolean getShowTutorialCards() {
    return showTutorialCards;
  }

  public void setShowTutorialCards(@javax.annotation.Nonnull Boolean showTutorialCards) {
    this.showTutorialCards = showTutorialCards;
  }


  public UserConfig notificationsEnabled(@javax.annotation.Nonnull Boolean notificationsEnabled) {
    this.notificationsEnabled = notificationsEnabled;
    return this;
  }

  /**
   * Get notificationsEnabled
   * @return notificationsEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getNotificationsEnabled() {
    return notificationsEnabled;
  }

  public void setNotificationsEnabled(@javax.annotation.Nonnull Boolean notificationsEnabled) {
    this.notificationsEnabled = notificationsEnabled;
  }


  public UserConfig allowEmailNotifications(@javax.annotation.Nonnull Boolean allowEmailNotifications) {
    this.allowEmailNotifications = allowEmailNotifications;
    return this;
  }

  /**
   * Get allowEmailNotifications
   * @return allowEmailNotifications
   */
  @javax.annotation.Nonnull
  public Boolean getAllowEmailNotifications() {
    return allowEmailNotifications;
  }

  public void setAllowEmailNotifications(@javax.annotation.Nonnull Boolean allowEmailNotifications) {
    this.allowEmailNotifications = allowEmailNotifications;
  }


  public UserConfig allowLiquidationsNotifications(@javax.annotation.Nonnull Boolean allowLiquidationsNotifications) {
    this.allowLiquidationsNotifications = allowLiquidationsNotifications;
    return this;
  }

  /**
   * Get allowLiquidationsNotifications
   * @return allowLiquidationsNotifications
   */
  @javax.annotation.Nonnull
  public Boolean getAllowLiquidationsNotifications() {
    return allowLiquidationsNotifications;
  }

  public void setAllowLiquidationsNotifications(@javax.annotation.Nonnull Boolean allowLiquidationsNotifications) {
    this.allowLiquidationsNotifications = allowLiquidationsNotifications;
  }


  public UserConfig allowDepositWithdrawalNotifications(@javax.annotation.Nonnull Boolean allowDepositWithdrawalNotifications) {
    this.allowDepositWithdrawalNotifications = allowDepositWithdrawalNotifications;
    return this;
  }

  /**
   * Get allowDepositWithdrawalNotifications
   * @return allowDepositWithdrawalNotifications
   */
  @javax.annotation.Nonnull
  public Boolean getAllowDepositWithdrawalNotifications() {
    return allowDepositWithdrawalNotifications;
  }

  public void setAllowDepositWithdrawalNotifications(@javax.annotation.Nonnull Boolean allowDepositWithdrawalNotifications) {
    this.allowDepositWithdrawalNotifications = allowDepositWithdrawalNotifications;
  }


  public UserConfig allowOrdersNotifications(@javax.annotation.Nonnull Boolean allowOrdersNotifications) {
    this.allowOrdersNotifications = allowOrdersNotifications;
    return this;
  }

  /**
   * Get allowOrdersNotifications
   * @return allowOrdersNotifications
   */
  @javax.annotation.Nonnull
  public Boolean getAllowOrdersNotifications() {
    return allowOrdersNotifications;
  }

  public void setAllowOrdersNotifications(@javax.annotation.Nonnull Boolean allowOrdersNotifications) {
    this.allowOrdersNotifications = allowOrdersNotifications;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserConfig userConfig = (UserConfig) o;
    return Objects.equals(this.id, userConfig.id) &&
        Objects.equals(this.photoUrl, userConfig.photoUrl) &&
        Objects.equals(this.timezone, userConfig.timezone) &&
        Objects.equals(this.createdAt, userConfig.createdAt) &&
        Objects.equals(this.updatedAt, userConfig.updatedAt) &&
        Objects.equals(this.showTutorialCards, userConfig.showTutorialCards) &&
        Objects.equals(this.notificationsEnabled, userConfig.notificationsEnabled) &&
        Objects.equals(this.allowEmailNotifications, userConfig.allowEmailNotifications) &&
        Objects.equals(this.allowLiquidationsNotifications, userConfig.allowLiquidationsNotifications) &&
        Objects.equals(this.allowDepositWithdrawalNotifications, userConfig.allowDepositWithdrawalNotifications) &&
        Objects.equals(this.allowOrdersNotifications, userConfig.allowOrdersNotifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, photoUrl, timezone, createdAt, updatedAt, showTutorialCards, notificationsEnabled, allowEmailNotifications, allowLiquidationsNotifications, allowDepositWithdrawalNotifications, allowOrdersNotifications);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserConfig {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    photoUrl: ").append(toIndentedString(photoUrl)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    showTutorialCards: ").append(toIndentedString(showTutorialCards)).append("\n");
    sb.append("    notificationsEnabled: ").append(toIndentedString(notificationsEnabled)).append("\n");
    sb.append("    allowEmailNotifications: ").append(toIndentedString(allowEmailNotifications)).append("\n");
    sb.append("    allowLiquidationsNotifications: ").append(toIndentedString(allowLiquidationsNotifications)).append("\n");
    sb.append("    allowDepositWithdrawalNotifications: ").append(toIndentedString(allowDepositWithdrawalNotifications)).append("\n");
    sb.append("    allowOrdersNotifications: ").append(toIndentedString(allowOrdersNotifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "photo_url", "timezone", "created_at", "updated_at", "show_tutorial_cards", "notifications_enabled", "allow_email_notifications", "allow_liquidations_notifications", "allow_deposit_withdrawal_notifications", "allow_orders_notifications"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "created_at", "updated_at", "show_tutorial_cards", "notifications_enabled", "allow_email_notifications", "allow_liquidations_notifications", "allow_deposit_withdrawal_notifications", "allow_orders_notifications"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UserConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UserConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in UserConfig is not found in the empty JSON string", UserConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UserConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UserConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UserConfig.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("photo_url") != null && !jsonObj.get("photo_url").isJsonNull()) && !jsonObj.get("photo_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `photo_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("photo_url").toString()));
      }
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<UserConfig>() {
           @Override
           public void write(JsonWriter out, UserConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UserConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UserConfig
   * @throws IOException if the JSON string is invalid with respect to UserConfig
   */
  public static UserConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserConfig.class);
  }

  /**
   * Convert an instance of UserConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

