/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.APIKeyResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.APIKeyResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.APIKeys.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AccountBalanceTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AccountPortfolioResponseV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AccountPortfolioV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AccountSummaryV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AccountV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AllPositions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AllPositionsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AllWithdrawalInitiationsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Asset.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AssetConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AssetPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AssetPriceResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AssetRequestError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.AssetYTM.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.BalanceTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.BalancesResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Bond.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CancelOrderResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Candle.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ClaimLeverageAccruedInterest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ClaimLeverageAccruedInterestRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ClaimLeverageAccruedInterestResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CloseAccountRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ClosePositionRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ClosePositionResp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ClosePositionResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Collateral.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CouponPayment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateAPIKeyData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateAPIKeyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateAPIKeyResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateConditionalOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateConditionalOrderResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateConditionalOrderResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateIntegratorUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateOrUpdateUserResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CreateOrderResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CurrentLeverageAccruedInterest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.CurrentLeverageAccruedInterestResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.DefundUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.FundUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.FundUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.FundUserResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.GetAssetByIDResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.GetAssetYTMByIDResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.GetRealizedPnlSettlementsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.GetTopOfBookResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.HistoricalLeverageInterestRate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.HistoricalLeverageInterestRates.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.HistoricalLeverageInterestRatesResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.IsolateCollateralRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.IsolateCollateralResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.IsolatedCollateral.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.IsolatedPosition.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LedgerAccountsResponseV2Envelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LedgerModuleByAssetResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LedgerModuleResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LeverageBalanceResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LeverageInterestRate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LeverageInterestRateResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LeverageModuleResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LeverageRequestError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LiquidationTargetsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Liquidity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LiquidityRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LiquidityResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListAccountsResponseV2Envelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListAssetPriceResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListCandlesResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListCouponPaymentsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListOrderBookDepthResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListOrderbookResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListOrdersResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListPositionAccountsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListPositionsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListTradeResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListTransactionsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListUserCouponPaymentsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ListUsersResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.LiveOrderbook.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Margin.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Metadata.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ModuleBalance.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.NewIsolatedAccountRequestV2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.NewIsolatedAccountResponseV2Envelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Order.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBook.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookBalance.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookDepth.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookHaltResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookResumeResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookSummary.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookSummaryResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookTerminateResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderBookTop.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderId.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderbookStats.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.OrderbookStatsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PLAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PLAsset.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PLResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PLSummary.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PayLeverageAccruedInterest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PayLeverageAccruedInterestRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PayLeverageAccruedInterestResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PoolPrice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PoolPriceResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PoolRequestError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Portfolio.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Position.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PositionAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PositionAsset.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PositionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.PriceLevel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.RealizedPnlSettlement.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.RealizedPnlSettlements.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ResponseEnvelopeOfListAssets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.RevokeAPIKeyData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.RevokeAPIKeyResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.SettleLeverageAccruedInterest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.SettleLeverageAccruedInterestRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.SettleLeverageAccruedInterestResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.SettleRealizedPnlRecordResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamAssetsEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamCandlesEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamCurrentLeverageAccruedInterestResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamOrderBookBalanceEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamOrderUpdatesEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamOrdersEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamPositionsEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamTradesEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamTransactionsEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamUserCouponPaymentsEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.StreamUserCouponPaymentsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Supply.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.SupplyRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.SupplyResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TenantRestrictions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Trade.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TradeRequestError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TradeResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Transaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransactionRequestError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransactionResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransactionsSettlement.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransactionsSettlementRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransactionsSettlementsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransactionsSettlementsResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransferAccountBalancesRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransferAccountBalancesResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransferBalancesRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransferBalancesResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.TransformedAssets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UnitePositionRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UnitePositionResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UnitedPosition.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UpdateFieldBoolean.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UpdateFieldString.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UpdateRolesString.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UpdateUserConfigRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.User.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserBalanceResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserConfigResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserCouponPayment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserCouponPaymentAssetSummary.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserCouponPaymentsResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserCreatedResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserDeletedResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserExistsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserInterest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserInterestResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserPositionResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserUpdatedResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.UserValueResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ValidateSubmitOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.ValidateSubmitOrderResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.Withdraw.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.WithdrawRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.WithdrawResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.WithdrawalInitiation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.WithdrawalInitiationResponseEnvelope.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new tech.dora.model.WithdrawalRequestReason.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
