/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountV2
 */
public class AccountV2Test {
    private final AccountV2 model = new AccountV2();

    /**
     * Model tests for AccountV2
     */
    @Test
    public void testAccountV2() {
        // TODO: test AccountV2
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'seq'
     */
    @Test
    public void seqTest() {
        // TODO: test seq
    }

    /**
     * Test the property 'isGlobal'
     */
    @Test
    public void isGlobalTest() {
        // TODO: test isGlobal
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'supplied'
     */
    @Test
    public void suppliedTest() {
        // TODO: test supplied
    }

    /**
     * Test the property 'borrowed'
     */
    @Test
    public void borrowedTest() {
        // TODO: test borrowed
    }

    /**
     * Test the property 'impendingBorrows'
     */
    @Test
    public void impendingBorrowsTest() {
        // TODO: test impendingBorrows
    }

    /**
     * Test the property 'avgEntryPrice'
     */
    @Test
    public void avgEntryPriceTest() {
        // TODO: test avgEntryPrice
    }

    /**
     * Test the property 'borrowLimit'
     */
    @Test
    public void borrowLimitTest() {
        // TODO: test borrowLimit
    }

    /**
     * Test the property 'liquidationThreshold'
     */
    @Test
    public void liquidationThresholdTest() {
        // TODO: test liquidationThreshold
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'pendingWithdrawal'
     */
    @Test
    public void pendingWithdrawalTest() {
        // TODO: test pendingWithdrawal
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

}
