/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import tech.dora.model.AffiliateCashFlow;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AffiliateCashFlowReport
 */
public class AffiliateCashFlowReportTest {
    private final AffiliateCashFlowReport model = new AffiliateCashFlowReport();

    /**
     * Model tests for AffiliateCashFlowReport
     */
    @Test
    public void testAffiliateCashFlowReport() {
        // TODO: test AffiliateCashFlowReport
    }

    /**
     * Test the property 'cashFlows'
     */
    @Test
    public void cashFlowsTest() {
        // TODO: test cashFlows
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    public void hasMoreTest() {
        // TODO: test hasMore
    }

}
