/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateConditionalOrderRequest
 */
public class CreateConditionalOrderRequestTest {
    private final CreateConditionalOrderRequest model = new CreateConditionalOrderRequest();

    /**
     * Model tests for CreateConditionalOrderRequest
     */
    @Test
    public void testCreateConditionalOrderRequest() {
        // TODO: test CreateConditionalOrderRequest
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'orderBookId'
     */
    @Test
    public void orderBookIdTest() {
        // TODO: test orderBookId
    }

    /**
     * Test the property 'positionId'
     */
    @Test
    public void positionIdTest() {
        // TODO: test positionId
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'stopLossPrice'
     */
    @Test
    public void stopLossPriceTest() {
        // TODO: test stopLossPrice
    }

    /**
     * Test the property 'takeProfitPrice'
     */
    @Test
    public void takeProfitPriceTest() {
        // TODO: test takeProfitPrice
    }

}
