/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderbookStats
 */
public class OrderbookStatsTest {
    private final OrderbookStats model = new OrderbookStats();

    /**
     * Model tests for OrderbookStats
     */
    @Test
    public void testOrderbookStats() {
        // TODO: test OrderbookStats
    }

    /**
     * Test the property 'orderBookId'
     */
    @Test
    public void orderBookIdTest() {
        // TODO: test orderBookId
    }

    /**
     * Test the property 'openPrice'
     */
    @Test
    public void openPriceTest() {
        // TODO: test openPrice
    }

    /**
     * Test the property 'lastPrice'
     */
    @Test
    public void lastPriceTest() {
        // TODO: test lastPrice
    }

    /**
     * Test the property 'high24h'
     */
    @Test
    public void high24hTest() {
        // TODO: test high24h
    }

    /**
     * Test the property 'low24h'
     */
    @Test
    public void low24hTest() {
        // TODO: test low24h
    }

    /**
     * Test the property 'change24h'
     */
    @Test
    public void change24hTest() {
        // TODO: test change24h
    }

    /**
     * Test the property 'changePct24h'
     */
    @Test
    public void changePct24hTest() {
        // TODO: test changePct24h
    }

    /**
     * Test the property 'volume24hBase'
     */
    @Test
    public void volume24hBaseTest() {
        // TODO: test volume24hBase
    }

    /**
     * Test the property 'volume24hUsd'
     */
    @Test
    public void volume24hUsdTest() {
        // TODO: test volume24hUsd
    }

}
