/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.ArrayList;
import java.util.List;
import tech.dora.model.PLAccount;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PLAccounts
 */
public class PLAccountsTest {
    private final PLAccounts model = new PLAccounts();

    /**
     * Model tests for PLAccounts
     */
    @Test
    public void testPLAccounts() {
        // TODO: test PLAccounts
    }

}
