/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import tech.dora.model.Margin;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PLAsset
 */
public class PLAssetTest {
    private final PLAsset model = new PLAsset();

    /**
     * Model tests for PLAsset
     */
    @Test
    public void testPLAsset() {
        // TODO: test PLAsset
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'side'
     */
    @Test
    public void sideTest() {
        // TODO: test side
    }

    /**
     * Test the property 'avgEntryPrice'
     */
    @Test
    public void avgEntryPriceTest() {
        // TODO: test avgEntryPrice
    }

    /**
     * Test the property 'markPrice'
     */
    @Test
    public void markPriceTest() {
        // TODO: test markPrice
    }

    /**
     * Test the property 'liquidationPrice'
     */
    @Test
    public void liquidationPriceTest() {
        // TODO: test liquidationPrice
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

    /**
     * Test the property 'borrowed'
     */
    @Test
    public void borrowedTest() {
        // TODO: test borrowed
    }

    /**
     * Test the property 'margin'
     */
    @Test
    public void marginTest() {
        // TODO: test margin
    }

    /**
     * Test the property 'unrealizedPl'
     */
    @Test
    public void unrealizedPlTest() {
        // TODO: test unrealizedPl
    }

    /**
     * Test the property 'leverageLimit'
     */
    @Test
    public void leverageLimitTest() {
        // TODO: test leverageLimit
    }

    /**
     * Test the property 'tp'
     */
    @Test
    public void tpTest() {
        // TODO: test tp
    }

    /**
     * Test the property 'sl'
     */
    @Test
    public void slTest() {
        // TODO: test sl
    }

    /**
     * Test the property 'initialCapital'
     */
    @Test
    public void initialCapitalTest() {
        // TODO: test initialCapital
    }

    /**
     * Test the property 'impendingBorrows'
     */
    @Test
    public void impendingBorrowsTest() {
        // TODO: test impendingBorrows
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'unusedCollateral'
     */
    @Test
    public void unusedCollateralTest() {
        // TODO: test unusedCollateral
    }

}
