/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PnLRankingSummary
 */
public class PnLRankingSummaryTest {
    private final PnLRankingSummary model = new PnLRankingSummary();

    /**
     * Model tests for PnLRankingSummary
     */
    @Test
    public void testPnLRankingSummary() {
        // TODO: test PnLRankingSummary
    }

    /**
     * Test the property 'allUsersDailyTradingVolume'
     */
    @Test
    public void allUsersDailyTradingVolumeTest() {
        // TODO: test allUsersDailyTradingVolume
    }

    /**
     * Test the property 'allUsersTotalTradingVolume'
     */
    @Test
    public void allUsersTotalTradingVolumeTest() {
        // TODO: test allUsersTotalTradingVolume
    }

}
