/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import java.util.ArrayList;
import java.util.List;
import tech.dora.model.StreamTradesEntry;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StreamTradesResponse
 */
public class StreamTradesResponseTest {
    private final StreamTradesResponse model = new StreamTradesResponse();

    /**
     * Model tests for StreamTradesResponse
     */
    @Test
    public void testStreamTradesResponse() {
        // TODO: test StreamTradesResponse
    }

}
