/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import tech.dora.model.Transaction;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StreamTransactionsEntry
 */
public class StreamTransactionsEntryTest {
    private final StreamTransactionsEntry model = new StreamTransactionsEntry();

    /**
     * Model tests for StreamTransactionsEntry
     */
    @Test
    public void testStreamTransactionsEntry() {
        // TODO: test StreamTransactionsEntry
    }

    /**
     * Test the property 'val'
     */
    @Test
    public void valTest() {
        // TODO: test val
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

}
