/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TradingChallengeResult
 */
public class TradingChallengeResultTest {
    private final TradingChallengeResult model = new TradingChallengeResult();

    /**
     * Model tests for TradingChallengeResult
     */
    @Test
    public void testTradingChallengeResult() {
        // TODO: test TradingChallengeResult
    }

    /**
     * Test the property 'tradingChallengeId'
     */
    @Test
    public void tradingChallengeIdTest() {
        // TODO: test tradingChallengeId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'userName'
     */
    @Test
    public void userNameTest() {
        // TODO: test userName
    }

    /**
     * Test the property 'cumVolume'
     */
    @Test
    public void cumVolumeTest() {
        // TODO: test cumVolume
    }

    /**
     * Test the property 'cumPnl'
     */
    @Test
    public void cumPnlTest() {
        // TODO: test cumPnl
    }

    /**
     * Test the property 'pnlPct'
     */
    @Test
    public void pnlPctTest() {
        // TODO: test pnlPct
    }

    /**
     * Test the property 'calendarDaysSinceStart'
     */
    @Test
    public void calendarDaysSinceStartTest() {
        // TODO: test calendarDaysSinceStart
    }

    /**
     * Test the property 'activeDays'
     */
    @Test
    public void activeDaysTest() {
        // TODO: test activeDays
    }

    /**
     * Test the property 'compliantDays'
     */
    @Test
    public void compliantDaysTest() {
        // TODO: test compliantDays
    }

    /**
     * Test the property 'crownEligible'
     */
    @Test
    public void crownEligibleTest() {
        // TODO: test crownEligible
    }

    /**
     * Test the property 'claimEligible'
     */
    @Test
    public void claimEligibleTest() {
        // TODO: test claimEligible
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'crown'
     */
    @Test
    public void crownTest() {
        // TODO: test crown
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deactivationStatus'
     */
    @Test
    public void deactivationStatusTest() {
        // TODO: test deactivationStatus
    }

    /**
     * Test the property 'currentDayDailyVolume'
     */
    @Test
    public void currentDayDailyVolumeTest() {
        // TODO: test currentDayDailyVolume
    }

    /**
     * Test the property 'currentDayDailyPnl'
     */
    @Test
    public void currentDayDailyPnlTest() {
        // TODO: test currentDayDailyPnl
    }

    /**
     * Test the property 'currentDayTradingDate'
     */
    @Test
    public void currentDayTradingDateTest() {
        // TODO: test currentDayTradingDate
    }

    /**
     * Test the property 'cumTrades'
     */
    @Test
    public void cumTradesTest() {
        // TODO: test cumTrades
    }

}
