/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransferAccountBalancesRequest
 */
public class TransferAccountBalancesRequestTest {
    private final TransferAccountBalancesRequest model = new TransferAccountBalancesRequest();

    /**
     * Model tests for TransferAccountBalancesRequest
     */
    @Test
    public void testTransferAccountBalancesRequest() {
        // TODO: test TransferAccountBalancesRequest
    }

    /**
     * Test the property 'fromAccountId'
     */
    @Test
    public void fromAccountIdTest() {
        // TODO: test fromAccountId
    }

    /**
     * Test the property 'toAccountId'
     */
    @Test
    public void toAccountIdTest() {
        // TODO: test toAccountId
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

}
