/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UnitePositionRequest
 */
public class UnitePositionRequestTest {
    private final UnitePositionRequest model = new UnitePositionRequest();

    /**
     * Model tests for UnitePositionRequest
     */
    @Test
    public void testUnitePositionRequest() {
        // TODO: test UnitePositionRequest
    }

    /**
     * Test the property 'globalPositionId'
     */
    @Test
    public void globalPositionIdTest() {
        // TODO: test globalPositionId
    }

}
