/*
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tech.dora.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import tech.dora.model.UserCouponPayment;
import tech.dora.model.UserCouponPaymentAssetSummary;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserCouponPaymentsResponseData
 */
public class UserCouponPaymentsResponseDataTest {
    private final UserCouponPaymentsResponseData model = new UserCouponPaymentsResponseData();

    /**
     * Model tests for UserCouponPaymentsResponseData
     */
    @Test
    public void testUserCouponPaymentsResponseData() {
        // TODO: test UserCouponPaymentsResponseData
    }

    /**
     * Test the property 'couponPayments'
     */
    @Test
    public void couponPaymentsTest() {
        // TODO: test couponPayments
    }

    /**
     * Test the property 'summaryByAsset'
     */
    @Test
    public void summaryByAssetTest() {
        // TODO: test summaryByAsset
    }

}
